package org.rsmod.content.areas.city.lumbridge.npcs

import jakarta.inject.Inject
import org.rsmod.api.script.onOpNpc2
import org.rsmod.api.shops.Shops
import org.rsmod.content.areas.city.lumbridge.configs.lumbridge_invs
import org.rsmod.content.areas.city.lumbridge.configs.lumbridge_npcs
import org.rsmod.game.entity.Npc
import org.rsmod.game.entity.Player
import org.rsmod.plugin.scripts.PluginScript
import org.rsmod.plugin.scripts.ScriptContext

/**
 * Staged shop handler: Lumbridge General Store
 * Generated by corpus-generators POC.
 * Inventory stock from generalshop1 (hand-written).
 */
class StagedLumbridgeGeneralStoreShop @Inject constructor(private val shops: Shops) : PluginScript() {
    override fun ScriptContext.startup() {
        onOpNpc2(lumbridge_npcs.lumbridge_shop_keeper) { player.openLumbridge_Shop_KeeperShop(it.npc) }
        onOpNpc2(lumbridge_npcs.lumbridge_shop_assistant) { player.openLumbridge_Shop_AssistantShop(it.npc) }
    }

    private fun Player.openLumbridge_Shop_KeeperShop(npc: Npc) {
        shops.open(this, npc, "Lumbridge General Store", lumbridge_invs.generalshop1)
    }

    private fun Player.openLumbridge_Shop_AssistantShop(npc: Npc) {
        shops.open(this, npc, "Lumbridge General Store", lumbridge_invs.generalshop1)
    }

}