@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.obj.ObjReferences

typealias objs = BaseObjs

object BaseObjs : ObjReferences() {
    val template_for_cert = find("template_for_cert")
    val template_for_transform = find("template_for_transform")
    val template_for_placeholder = find("template_for_placeholder")
    val null_item_placeholder = find("blankobject")

    val coins = find("coins")
    val platinum_tokens = find("platinum")

    val bones = find("bones")
    val big_bones = find("big_bones")
    val ashes = find("ashes")

    // Bones — sym names confirmed against obj.sym (rev 228 cache)
    val burnt_bones = find("bones_burnt")
    val bat_bones = find("bat_bones")
    val wolf_bones = find("wolf_bones")
    val babydragon_bones = find("babydragon_bones")
    val dragon_bones = find("dragon_bones")
    val wyvern_bones = find("wyvern_bones")
    val wyrm_bones = find("wyrm_bones")
    val drake_bones = find("drake_bones")
    val hydra_bones = find("hydra_bones")
    val lava_dragon_bones = find("lava_dragon_bones")
    val dagannoth_bones = find("dagannoth_king_bones")
    val superior_dragon_bones = find("dragon_bones_superior")
    val jogre_bones = find("tbwt_jogre_bones")
    val zogre_bones = find("zogre_bones")
    val fayrg_bones = find("zogre_ancestral_bones_fayg")
    val raurg_bones = find("zogre_ancestral_bones_raurg")
    val ourg_bones = find("zogre_ancestral_bones_ourg")
    val snowball = find("gublinch_snowball")

    val pot_empty = find("pot_empty")
    val jug_empty = find("jug_empty")
    val pack_jug_empty = find("pack_jug_empty")
    val shears = find("shears")
    val knife = find("knife")
    val bucket_empty = find("bucket_empty")
    val bucket_of_milk = find("bucket_milk")
    val pack_bucket = find("pack_bucket")
    val bowl_empty = find("bowl_empty")
    val cake_tin = find("cake_tin")
    val tinderbox = find("tinderbox")
    val chisel = find("chisel")
    val spade = find("spade")
    val hammer = find("hammer")
    val newcomer_map = find("newcomer_map")
    val sos_security_book = find("sos_security_book")
    val wool = find("wool")
    val ball_of_wool = find("ball_of_wool")

    val cabbage = find("cabbage")
    val onion = find("onion")
    val grain = find("grain")
    val potato = find("potato")
    val cabbage_seed = find("cabbage_seed")
    val egg = find("egg")
    val pot_of_flour = find("pot_flour")

    val bobs_axe_flyer = find("flier")
    val iron_battleaxe = find("iron_battleaxe")
    val steel_battleaxe = find("steel_battleaxe")
    val mithril_battleaxe = find("mithril_battleaxe")
    val beer = find("beer")
    val charcoal = find("charcoal")

    val logs = find("logs")
    val oak_logs = find("oak_logs")
    val willow_logs = find("willow_logs")
    val maple_logs = find("maple_logs")
    val yew_logs = find("yew_logs")
    val magic_logs = find("magic_logs")
    val redwood_logs = find("redwood_logs")
    val teak_logs = find("teak_logs")
    val mahogany_logs = find("mahogany_logs")
    val achey_tree_logs = find("achey_tree_logs")
    val arctic_pine_logs = find("arctic_pine_log")
    val blisterwood_logs = find("blisterwood_logs")
    val juniper_logs = find("juniper_logs")
    val bark = find("hollow_bark")

    val coal_bag = find("coal_bag")
    val coal_bag_open = find("coal_bag_open")
    val rcu_pouch_small = find("rcu_pouch_small")
    val rcu_pouch_medium = find("rcu_pouch_medium")
    val rcu_pouch_medium_degrade = find("rcu_pouch_medium_degrade")
    val rcu_pouch_large = find("rcu_pouch_large")
    val rcu_pouch_large_degrade = find("rcu_pouch_large_degrade")
    val rcu_pouch_giant = find("rcu_pouch_giant")
    val rcu_pouch_giant_degrade = find("rcu_pouch_giant_degrade")
    val rcu_pouch_colossal = find("rcu_pouch_colossal")
    val rcu_pouch_colossal_degrade = find("rcu_pouch_colossal_degrade")

    val cabbage_cape = find("skillcape_cabbage")

    val music_cape = find("music_cape_trimmed")
    val music_cape_t = find("music_cape_trimmed")
    val music_hood = find("music_cape_hood")

    val quest_point_cape = find("skillcape_qp")
    val quest_point_cape_t = find("skillcape_qp_trimmed")
    val quest_point_hood = find("skillcape_qp_hood")

    val achievement_diary_cape = find("skillcape_ad")
    val achievement_diary_cape_t = find("skillcape_ad_trimmed")
    val achievement_diary_hood = find("skillcape_ad_hood")

    val max_hood = find("skillcape_max_hood")
    val max_cape_worn = find("skillcape_max_worn")
    val max_cape_inv = find("skillcape_max")

    val attack_skillcape = find("skillcape_attack")
    val attack_skillcape_t = find("skillcape_attack_trimmed")
    val attack_hood = find("skillcape_attack_hood")

    val defence_skillcape = find("skillcape_defence")
    val defence_skillcape_t = find("skillcape_defence_trimmed")
    val defence_hood = find("skillcape_defence_hood")

    val strength_skillcape = find("skillcape_strength")
    val strength_skillcape_t = find("skillcape_strength_trimmed")
    val strength_hood = find("skillcape_strength_hood")

    val hitpoints_skillcape = find("skillcape_hitpoints")
    val hitpoints_skillcape_t = find("skillcape_hitpoints_trimmed")
    val hitpoints_hood = find("skillcape_hitpoints_hood")

    val ranged_skillcape = find("skillcape_ranging")
    val ranged_skillcape_t = find("skillcape_ranging_trimmed")
    val ranged_hood = find("skillcape_ranging_hood")

    val prayer_skillcape = find("skillcape_prayer")
    val prayer_skillcape_t = find("skillcape_prayer_trimmed")
    val prayer_hood = find("skillcape_prayer_hood")

    val magic_skillcape = find("skillcape_magic")
    val magic_skillcape_t = find("skillcape_magic_trimmed")
    val magic_hood = find("skillcape_magic_hood")

    val cooking_skillcape = find("skillcape_cooking")
    val cooking_skillcape_t = find("skillcape_cooking_trimmed")
    val cooking_hood = find("skillcape_cooking_hood")

    val woodcutting_skillcape = find("skillcape_woodcutting")
    val woodcutting_skillcape_t = find("skillcape_woodcutting_trimmed")
    val woodcutting_hood = find("skillcape_woodcutting_hood")

    val fletching_skillcape = find("skillcape_fletching")
    val fletching_skillcape_t = find("skillcape_fletching_trimmed")
    val fletching_hood = find("skillcape_fletching_hood")

    val fishing_skillcape = find("skillcape_fishing")
    val fishing_skillcape_t = find("skillcape_fishing_trimmed")
    val fishing_hood = find("skillcape_fishing_hood")

    val firemaking_skillcape = find("skillcape_firemaking")
    val firemaking_skillcape_t = find("skillcape_firemaking_trimmed")
    val firemaking_hood = find("skillcape_firemaking_hood")

    val crafting_skillcape = find("skillcape_crafting")
    val crafting_skillcape_t = find("skillcape_crafting_trimmed")
    val crafting_hood = find("skillcape_crafting_hood")

    val smithing_skillcape = find("skillcape_smithing")
    val smithing_skillcape_t = find("skillcape_smithing_trimmed")
    val smithing_hood = find("skillcape_smithing_hood")

    val mining_skillcape = find("skillcape_mining")
    val mining_skillcape_t = find("skillcape_mining_trimmed")
    val mining_hood = find("skillcape_mining_hood")

    val herblore_skillcape = find("skillcape_herblore")
    val herblore_skillcape_t = find("skillcape_herblore_trimmed")
    val herblore_hood = find("skillcape_herblore_hood")

    val agility_skillcape = find("skillcape_agility")
    val agility_skillcape_t = find("skillcape_agility_trimmed")
    val agility_hood = find("skillcape_agility_hood")

    val thieving_skillcape = find("skillcape_thieving")
    val thieving_skillcape_t = find("skillcape_thieving_trimmed")
    val thieving_hood = find("skillcape_thieving_hood")

    val slayer_skillcape = find("skillcape_slayer")
    val slayer_skillcape_t = find("skillcape_slayer_trimmed")
    val slayer_hood = find("skillcape_slayer_hood")

    val farming_skillcape = find("skillcape_farming")
    val farming_skillcape_t = find("skillcape_farming_trimmed")
    val farming_hood = find("skillcape_farming_hood")

    val runecrafting_skillcape = find("skillcape_runecrafting")
    val runecrafting_skillcape_t = find("skillcape_runecrafting_trimmed")
    val runecrafting_hood = find("skillcape_runecrafting_hood")

    val hunter_skillcape = find("skillcape_hunting")
    val hunter_skillcape_t = find("skillcape_hunting_trimmed")
    val hunter_hood = find("skillcape_hunting_hood")

    val construction_skillcape = find("skillcape_construction")
    val construction_skillcape_t = find("skillcape_construction_trimmed")
    val construction_hood = find("skillcape_construction_hood")

    val lumberjack_hat = find("ramble_lumberjack_hat")
    val lumberjack_top = find("ramble_lumberjack_top")
    val lumberjack_legs = find("ramble_lumberjack_legs")
    val lumberjack_boots = find("ramble_lumberjack_boots")

    val forestry_hat = find("forestry_lumberjack_hat")
    val forestry_top = find("forestry_lumberjack_top")
    val forestry_legs = find("forestry_lumberjack_legs")
    val forestry_boots = find("forestry_lumberjack_boots")

    val graceful_hood_inv = find("graceful_hood")
    val graceful_cape_inv = find("graceful_cape")
    val graceful_top_inv = find("graceful_top")
    val graceful_legs_inv = find("graceful_legs")
    val graceful_gloves_inv = find("graceful_gloves")
    val graceful_boots_inv = find("graceful_boots")

    val graceful_hood_worn = find("graceful_hood_worn")
    val graceful_cape_worn = find("graceful_cape_worn")
    val graceful_top_worn = find("graceful_top_worn")
    val graceful_legs_worn = find("graceful_legs_worn")
    val graceful_gloves_worn = find("graceful_gloves_worn")
    val graceful_boots_worn = find("graceful_boots_worn")

    val arceuus_graceful_hood_inv = find("zeah_graceful_hood_arceuus")
    val arceuus_graceful_cape_inv = find("zeah_graceful_cape_arceuus")
    val arceuus_graceful_top_inv = find("zeah_graceful_top_arceuus")
    val arceuus_graceful_legs_inv = find("zeah_graceful_legs_arceuus")
    val arceuus_graceful_gloves_inv = find("zeah_graceful_gloves_arceuus")
    val arceuus_graceful_boots_inv = find("zeah_graceful_boots_arceuus")

    val arceuus_graceful_hood_worn = find("zeah_graceful_hood_arceuus_worn")
    val arceuus_graceful_cape_worn = find("zeah_graceful_cape_arceuus_worn")
    val arceuus_graceful_top_worn = find("zeah_graceful_top_arceuus_worn")
    val arceuus_graceful_legs_worn = find("zeah_graceful_legs_arceuus_worn")
    val arceuus_graceful_gloves_worn = find("zeah_graceful_gloves_arceuus_worn")
    val arceuus_graceful_boots_worn = find("zeah_graceful_boots_arceuus_worn")

    val piscarilius_graceful_hood_inv = find("zeah_graceful_hood_piscarilius")
    val piscarilius_graceful_cape_inv = find("zeah_graceful_cape_piscarilius")
    val piscarilius_graceful_top_inv = find("zeah_graceful_top_piscarilius")
    val piscarilius_graceful_legs_inv = find("zeah_graceful_legs_piscarilius")
    val piscarilius_graceful_gloves_inv = find("zeah_graceful_gloves_piscarilius")
    val piscarilius_graceful_boots_inv = find("zeah_graceful_boots_piscarilius")

    val piscarilius_graceful_hood_worn = find("zeah_graceful_hood_piscarilius_worn")
    val piscarilius_graceful_cape_worn = find("zeah_graceful_cape_piscarilius_worn")
    val piscarilius_graceful_top_worn = find("zeah_graceful_top_piscarilius_worn")
    val piscarilius_graceful_legs_worn = find("zeah_graceful_legs_piscarilius_worn")
    val piscarilius_graceful_gloves_worn = find("zeah_graceful_gloves_piscarilius_worn")
    val piscarilius_graceful_boots_worn = find("zeah_graceful_boots_piscarilius_worn")

    val lovakengj_graceful_hood_inv = find("zeah_graceful_hood_lovakengj")
    val lovakengj_graceful_cape_inv = find("zeah_graceful_cape_lovakengj")
    val lovakengj_graceful_top_inv = find("zeah_graceful_top_lovakengj")
    val lovakengj_graceful_legs_inv = find("zeah_graceful_legs_lovakengj")
    val lovakengj_graceful_gloves_inv = find("zeah_graceful_gloves_lovakengj")
    val lovakengj_graceful_boots_inv = find("zeah_graceful_boots_lovakengj")

    val lovakengj_graceful_hood_worn = find("zeah_graceful_hood_lovakengj_worn")
    val lovakengj_graceful_cape_worn = find("zeah_graceful_cape_lovakengj_worn")
    val lovakengj_graceful_top_worn = find("zeah_graceful_top_lovakengj_worn")
    val lovakengj_graceful_legs_worn = find("zeah_graceful_legs_lovakengj_worn")
    val lovakengj_graceful_gloves_worn = find("zeah_graceful_gloves_lovakengj_worn")
    val lovakengj_graceful_boots_worn = find("zeah_graceful_boots_lovakengj_worn")

    val shayzien_graceful_hood_inv = find("zeah_graceful_hood_shayzien")
    val shayzien_graceful_cape_inv = find("zeah_graceful_cape_shayzien")
    val shayzien_graceful_top_inv = find("zeah_graceful_top_shayzien")
    val shayzien_graceful_legs_inv = find("zeah_graceful_legs_shayzien")
    val shayzien_graceful_gloves_inv = find("zeah_graceful_gloves_shayzien")
    val shayzien_graceful_boots_inv = find("zeah_graceful_boots_shayzien")

    val shayzien_graceful_hood_worn = find("zeah_graceful_hood_shayzien_worn")
    val shayzien_graceful_cape_worn = find("zeah_graceful_cape_shayzien_worn")
    val shayzien_graceful_top_worn = find("zeah_graceful_top_shayzien_worn")
    val shayzien_graceful_legs_worn = find("zeah_graceful_legs_shayzien_worn")
    val shayzien_graceful_gloves_worn = find("zeah_graceful_gloves_shayzien_worn")
    val shayzien_graceful_boots_worn = find("zeah_graceful_boots_shayzien_worn")

    val hosidius_graceful_hood_inv = find("zeah_graceful_hood_hosidius")
    val hosidius_graceful_cape_inv = find("zeah_graceful_cape_hosidius")
    val hosidius_graceful_top_inv = find("zeah_graceful_top_hosidius")
    val hosidius_graceful_legs_inv = find("zeah_graceful_legs_hosidius")
    val hosidius_graceful_gloves_inv = find("zeah_graceful_gloves_hosidius")
    val hosidius_graceful_boots_inv = find("zeah_graceful_boots_hosidius")

    val hosidius_graceful_hood_worn = find("zeah_graceful_hood_hosidius_worn")
    val hosidius_graceful_cape_worn = find("zeah_graceful_cape_hosidius_worn")
    val hosidius_graceful_top_worn = find("zeah_graceful_top_hosidius_worn")
    val hosidius_graceful_legs_worn = find("zeah_graceful_legs_hosidius_worn")
    val hosidius_graceful_gloves_worn = find("zeah_graceful_gloves_hosidius_worn")
    val hosidius_graceful_boots_worn = find("zeah_graceful_boots_hosidius_worn")

    val kourend_graceful_hood_inv = find("zeah_graceful_hood_kourend")
    val kourend_graceful_cape_inv = find("zeah_graceful_cape_kourend")
    val kourend_graceful_top_inv = find("zeah_graceful_top_kourend")
    val kourend_graceful_legs_inv = find("zeah_graceful_legs_kourend")
    val kourend_graceful_gloves_inv = find("zeah_graceful_gloves_kourend")
    val kourend_graceful_boots_inv = find("zeah_graceful_boots_kourend")

    val kourend_graceful_hood_worn = find("zeah_graceful_hood_kourend_worn")
    val kourend_graceful_cape_worn = find("zeah_graceful_cape_kourend_worn")
    val kourend_graceful_top_worn = find("zeah_graceful_top_kourend_worn")
    val kourend_graceful_legs_worn = find("zeah_graceful_legs_kourend_worn")
    val kourend_graceful_gloves_worn = find("zeah_graceful_gloves_kourend_worn")
    val kourend_graceful_boots_worn = find("zeah_graceful_boots_kourend_worn")

    val skillcape_graceful_hood_inv = find("graceful_hood_skillcapecolour")
    val skillcape_graceful_cape_inv = find("graceful_cape_skillcapecolour")
    val skillcape_graceful_top_inv = find("graceful_top_skillcapecolour")
    val skillcape_graceful_legs_inv = find("graceful_legs_skillcapecolour")
    val skillcape_graceful_gloves_inv = find("graceful_gloves_skillcapecolour")
    val skillcape_graceful_boots_inv = find("graceful_boots_skillcapecolour")

    val skillcape_graceful_hood_worn = find("graceful_hood_skillcapecolour_worn")
    val skillcape_graceful_cape_worn = find("graceful_cape_skillcapecolour_worn")
    val skillcape_graceful_top_worn = find("graceful_top_skillcapecolour_worn")
    val skillcape_graceful_legs_worn = find("graceful_legs_skillcapecolour_worn")
    val skillcape_graceful_gloves_worn = find("graceful_gloves_skillcapecolour_worn")
    val skillcape_graceful_boots_worn = find("graceful_boots_skillcapecolour_worn")

    val hallowed_graceful_hood_inv = find("graceful_hood_hallowed")
    val hallowed_graceful_cape_inv = find("graceful_cape_hallowed")
    val hallowed_graceful_top_inv = find("graceful_top_hallowed")
    val hallowed_graceful_legs_inv = find("graceful_legs_hallowed")
    val hallowed_graceful_gloves_inv = find("graceful_gloves_hallowed")
    val hallowed_graceful_boots_inv = find("graceful_boots_hallowed")

    val hallowed_graceful_hood_worn = find("graceful_hood_hallowed_worn")
    val hallowed_graceful_cape_worn = find("graceful_cape_hallowed_worn")
    val hallowed_graceful_top_worn = find("graceful_top_hallowed_worn")
    val hallowed_graceful_legs_worn = find("graceful_legs_hallowed_worn")
    val hallowed_graceful_gloves_worn = find("graceful_gloves_hallowed_worn")
    val hallowed_graceful_boots_worn = find("graceful_boots_hallowed_worn")

    val trailblazer_graceful_hood_inv = find("graceful_hood_trailblazer")
    val trailblazer_graceful_cape_inv = find("graceful_cape_trailblazer")
    val trailblazer_graceful_top_inv = find("graceful_top_trailblazer")
    val trailblazer_graceful_legs_inv = find("graceful_legs_trailblazer")
    val trailblazer_graceful_gloves_inv = find("graceful_gloves_trailblazer")
    val trailblazer_graceful_boots_inv = find("graceful_boots_trailblazer")

    val trailblazer_graceful_hood_worn = find("graceful_hood_trailblazer_worn")
    val trailblazer_graceful_cape_worn = find("graceful_cape_trailblazer_worn")
    val trailblazer_graceful_top_worn = find("graceful_top_trailblazer_worn")
    val trailblazer_graceful_legs_worn = find("graceful_legs_trailblazer_worn")
    val trailblazer_graceful_gloves_worn = find("graceful_gloves_trailblazer_worn")
    val trailblazer_graceful_boots_worn = find("graceful_boots_trailblazer_worn")

    val adventurer_graceful_hood_inv = find("graceful_hood_adventurer")
    val adventurer_graceful_cape_inv = find("graceful_cape_adventurer")
    val adventurer_graceful_top_inv = find("graceful_top_adventurer")
    val adventurer_graceful_legs_inv = find("graceful_legs_adventurer")
    val adventurer_graceful_gloves_inv = find("graceful_gloves_adventurer")
    val adventurer_graceful_boots_inv = find("graceful_boots_adventurer")

    val adventurer_graceful_hood_worn = find("graceful_hood_adventurer_worn")
    val adventurer_graceful_cape_worn = find("graceful_cape_adventurer_worn")
    val adventurer_graceful_top_worn = find("graceful_top_adventurer_worn")
    val adventurer_graceful_legs_worn = find("graceful_legs_adventurer_worn")
    val adventurer_graceful_gloves_worn = find("graceful_gloves_adventurer_worn")
    val adventurer_graceful_boots_worn = find("graceful_boots_adventurer_worn")

    val wyrm_graceful_hood_inv = find("graceful_hood_wyrm")
    val wyrm_graceful_cape_inv = find("graceful_cape_wyrm")
    val wyrm_graceful_top_inv = find("graceful_top_wyrm")
    val wyrm_graceful_legs_inv = find("graceful_legs_wyrm")
    val wyrm_graceful_gloves_inv = find("graceful_gloves_wyrm")
    val wyrm_graceful_boots_inv = find("graceful_boots_wyrm")

    val wyrm_graceful_hood_worn = find("graceful_hood_wyrm_worn")
    val wyrm_graceful_cape_worn = find("graceful_cape_wyrm_worn")
    val wyrm_graceful_top_worn = find("graceful_top_wyrm_worn")
    val wyrm_graceful_legs_worn = find("graceful_legs_wyrm_worn")
    val wyrm_graceful_gloves_worn = find("graceful_gloves_wyrm_worn")
    val wyrm_graceful_boots_worn = find("graceful_boots_wyrm_worn")

    val bronze_axe = find("bronze_axe")
    val iron_axe = find("iron_axe")
    val steel_axe = find("steel_axe")
    val black_axe = find("black_axe")
    val mithril_axe = find("mithril_axe")
    val adamant_axe = find("adamant_axe")
    val blessed_axe = find("anma_axe")
    val rune_axe = find("rune_axe")
    val gilded_axe = find("trail_gilded_axe")
    val dragon_axe = find("dragon_axe")
    val dragon_axe_or = find("trailblazer_axe_no_infernal")
    val third_age_axe = find("3a_axe")
    val infernal_axe = find("infernal_axe")
    val infernal_axe_or = find("trailblazer_axe")
    val crystal_axe = find("crystal_axe")

    val bronze_pickaxe = find("bronze_pickaxe")
    val iron_pickaxe = find("iron_pickaxe")
    val steel_pickaxe = find("steel_pickaxe")
    val black_pickaxe = find("black_pickaxe")
    val mithril_pickaxe = find("mithril_pickaxe")
    val adamant_pickaxe = find("adamant_pickaxe")
    val rune_pickaxe = find("rune_pickaxe")
    val gilded_pickaxe = find("trail_gilded_pickaxe")
    val dragon_pickaxe = find("dragon_pickaxe")
    val dragon_pickaxe_upgraded = find("dragon_pickaxe_pretty")
    val dragon_pickaxe_or_trailblazer = find("trailblazer_pickaxe_no_infernal")
    val dragon_pickaxe_or_zalcano = find("zalcano_pickaxe")
    val infernal_pickaxe = find("infernal_pickaxe")
    val infernal_pickaxe_uncharged = find("infernal_pickaxe_empty")
    val infernal_pickaxe_or = find("trailblazer_pickaxe")
    val infernal_pickaxe_or_uncharged = find("trailblazer_pickaxe_empty")
    val third_age_pickaxe = find("3a_pickaxe")
    val crystal_pickaxe = find("crystal_pickaxe")

    val dragon_harpoon = find("dragon_harpoon")
    val dragon_harpoon_or = find("trailblazer_harpoon_no_infernal")
    val infernal_harpoon = find("infernal_harpoon")
    val infernal_harpoon_or = find("trailblazer_harpoon")
    val infernal_harpoon_or_uncharged = find("trailblazer_harpoon_empty")
    val crystal_harpoon = find("crystal_harpoon")

    // Fishing tools
    val small_fishing_net = find("small_fishing_net")
    val big_fishing_net = find("big_fishing_net")
    val fishing_rod = find("fishing_rod")
    val fly_fishing_rod = find("fly_fishing_rod")
    val barbarian_rod = find("barbarian_rod")
    val lobster_pot = find("lobster_pot")
    val harpoon = find("harpoon")
    val oily_fishing_rod = find("oily_fishing_rod")
    val dark_crab_pot = find("dark_crab_pot")

    // Fishing consumables
    val fishing_bait = find("fishing_bait")
    val feather = find("feather")

    // Raw fish — sym names follow raw_xxx convention; validate against obj.sym if catches fail
    val raw_shrimps = find("raw_shrimps") // TODO: verify sym — may be "shrimp" (ID 317)
    val raw_anchovies = find("raw_anchovies")
    val raw_sardine = find("raw_sardine")
    val raw_mackerel = find("raw_mackerel")
    val raw_trout = find("raw_trout")
    val raw_cod = find("raw_cod")
    val raw_pike = find("raw_pike")
    val raw_salmon = find("raw_salmon")
    val raw_tuna = find("raw_tuna")
    val raw_lobster = find("raw_lobster")
    val raw_bass = find("raw_bass")
    val raw_swordfish = find("raw_swordfish")
    val raw_monkfish = find("raw_monkfish")
    val raw_shark = find("raw_shark")
    val raw_anglerfish = find("raw_anglerfish")
    val raw_dark_crab = find("raw_dark_crab")
    val leaping_trout = find("leaping_trout")
    val leaping_salmon = find("leaping_salmon")
    val leaping_sturgeon = find("leaping_sturgeon")

    val shrimps = find("shrimp")
    val raw_herring = find("raw_herring")
    val herring = find("herring")

    val nose_peg = find("slayer_nosepeg")
    val facemask = find("slayer_facemask")
    val earmuffs = find("slayer_earmuffs")
    val spiny_helmet = find("wallbeast_spike_helmet")
    val reinforced_goggles = find("slayer_reinforced_goggles")
    val neitiznot_shield = find("fremmenik_round_shield")

    val rune_pouch = find("bh_rune_pouch")
    val rune_pouch_l = find("bh_rune_pouch_trouver")
    val divine_rune_pouch = find("divine_rune_pouch")
    val divine_rune_pouch_l = find("divine_rune_pouch_trouver")

    val lms_rune_pouch = find("br_rune_replacement")

    val air_rune = find("airrune")
    val water_rune = find("waterrune")
    val earth_rune = find("earthrune")
    val fire_rune = find("firerune")
    val mind_rune = find("mindrune")
    val chaos_rune = find("chaosrune")
    val death_rune = find("chaosrune")
    val blood_rune = find("bloodrune")
    val body_rune = find("bodyrune")
    val nature_rune = find("naturerune")
    val law_rune = find("lawrune")
    val smoke_rune = find("smokerune")
    val mist_rune = find("mistrune")
    val dust_rune = find("dustrune")
    val steam_rune = find("steamrune")
    val lava_rune = find("lavarune")
    val mud_rune = find("mudrune")
    val soul_rune = find("soulrune")
    val sunfire_rune = find("sunfirerune")

    val air_rune_nz = find("nzone_airrune")
    val water_rune_nz = find("nzone_waterrune")
    val earth_rune_nz = find("nzone_earthrune")
    val fire_rune_nz = find("nzone_firerune")
    val chaos_rune_nz = find("nzone_chaosrune")
    val death_rune_nz = find("nzone_deathrune")
    val blood_rune_nz = find("nzone_bloodrune")

    val fake_air_rune = find("fake_airrune")
    val fake_water_rune = find("fake_waterrune")
    val fake_earth_rune = find("fake_earthrune")
    val fake_fire_rune = find("fake_firerune")
    val fake_nature_rune = find("fake_naturerune")

    val chaos_gauntlets = find("gauntlets_of_chaos")
    val tome_of_water = find("tome_of_water")
    val tome_of_earth = find("tome_of_earth")
    val tome_of_fire = find("tome_of_fire")
    val devils_element = find("devils_element")

    val air_staff = find("staff_of_air")
    val air_battlestaff = find("air_battlestaff")
    val mystic_air_staff = find("mystic_air_staff")

    val smoke_battlestaff = find("smoke_battlestaff")
    val mystic_smoke_staff = find("mystic_smoke_battlestaff")
    val mist_battlestaff = find("mist_battlestaff")
    val mystic_mist_staff = find("mystic_mist_battlestaff")
    val dust_battlestaff = find("dust_battlestaff")
    val mystic_dust_staff = find("mystic_dust_battlestaff")
    val twinflame_staff = find("twinflame_staff")

    val ancient_staff = find("staff_of_zaros")
    val skull_sceptre_i = find("sos_skull_sceptre_imbued")
    val ibans_staff = find("ibanstaff")
    val ibans_staff_u = find("ibanstaff_upgraded")
    val slayers_staff = find("slayer_staff")
    val slayers_staff_e = find("slayer_staff_enchanted")
    val thammarons_sceptre = find("wild_cave_sceptre_charged")
    val thammarons_sceptre_a = find("wild_cave_sceptre_charged_recol")
    val thammarons_sceptre_au = find("wild_cave_sceptre_uncharged_recol")
    val accursed_sceptre = find("wild_cave_accursed_charged")
    val accursed_sceptre_a = find("wild_cave_accursed_charged_recol")
    val accursed_sceptre_au = find("wild_cave_accursed_uncharged_recol")
    val staff_of_the_dead = find("sotd")
    val toxic_staff_of_the_dead = find("toxic_sotd_charged")
    val toxic_staff_uncharged = find("toxic_sotd")
    val staff_of_light = find("staff_of_light")
    val staff_of_balance = find("staff_of_balance")
    val void_knight_mace = find("pest_void_knight_mace")
    val void_knight_mace_l = find("pest_void_knight_mace_trouver")
    val bryophytas_staff = find("nature_staff_charged")
    val purging_staff = find("purging_staff")

    val saradomin_staff = find("saradomin_staff")
    val zamorak_staff = find("zamorak_staff")
    val guthix_staff = find("guthix_staff")
    val guthix_staff_rune = find("pest_interface_staffs")

    val view_jewellery_enchantment_spells = find("placeholder_blighted_sack_wave")
    val view_bolt_enchantment_spells = find("50_slayer_dart")

    val spell_enchant_lvl_1 = find("07_enchant_amulet_lvl1")
    val spell_enchant_lvl_2 = find("27_enchant_amulet_lvl2")
    val spell_enchant_lvl_3 = find("49_enchant_amulet_lvl3")
    val spell_enchant_lvl_4 = find("57_enchant_amulet_lvl4")
    val spell_enchant_lvl_5 = find("68_enchant_amulet_lvl5")
    val spell_enchant_lvl_6 = find("87_enchant_amulet_lvl6")
    val spell_enchant_lvl_7 = find("93_enchant_amulet_lvl7")
    val spell_bones_to_bananas = find("15_bones_bananas")
    val spell_bones_to_peaches = find("60_bones_peaches")
    val spell_low_alchemy = find("21_low_alchemy")
    val spell_high_alchemy = find("55_high_alchemy")
    val spell_superheat = find("43_superheat_item")
    val spell_tele_grab = find("33_tele_grab")
    val spell_monster_inspect = find("placeholder_gathering_event_leprechaun_charm")
    val spell_chargeorb_water = find("56_charge_water_orb")
    val spell_chargeorb_earth = find("60_charge_earth_orb")
    val spell_chargeorb_fire = find("63_charge_fire_orb")
    val spell_chargeorb_air = find("66_charge_air_orb")
    val spell_charge = find("80_charge")

    val spell_hometeleport_lumbridge = find("48_home_teleport")
    val spell_lumbridge_teleport = find("31_lumbridge_teleport")
    val spell_varrock_teleport = find("25_varrock_teleport")
    val spell_falador_teleport = find("37_falador_teleport")
    val spell_poh_teleport = find("67_house_teleport")
    val spell_camelot_teleport = find("45_camelot_teleport")
    val spell_kourendcastle_teleport = find("cert_deadman_level99_lamp")
    val spell_ardougne_teleport = find("51_ardougne_teleport")
    val spell_civitas_fortis_teleport = find("placeholder_blighted_sack_snare")
    val spell_watchtower_teleport = find("58_watchtower_teleport")
    val spell_trollheim_teleport = find("61_trollheim_teleport")
    val spell_apeatoll_teleport = find("64_ape_atoll_teleport")
    val spell_teleother_lumbridge = find("74_teleother_lumbridge")
    val spell_teleother_falador = find("82_teleother_falador")
    val spell_teleother_camelot = find("90_teleother_camelot")

    val spell_tele_block = find("85_teleport_block")
    val spell_teleport_to_target = find("placeholder_caveorb4dot")

    val spell_crumble_undead = find("39_crumble_undead")
    val spell_iban_blast = find("50_iban_blast")
    val spell_magic_dart = find("50_magic_dart")
    val spell_flames_of_zamorak = find("60_flames_of_zamorak")
    val spell_saradomin_strike = find("60_saradomin_strike")
    val spell_claws_of_guthix = find("60_claws_of_guthix")

    val spell_confuse = find("03_confuse")
    val spell_weaken = find("11_weaken")
    val spell_curse = find("19_curse")

    val spell_bind = find("20_bind")
    val spell_snare = find("50_snare")
    val spell_entangle = find("79_entangle")

    val spell_vulnerability = find("66_vulnerability")
    val spell_enfeeble = find("73_enfeeble")
    val spell_stun = find("80_stun")

    val spell_wind_strike = find("01_wind_strike")
    val spell_water_strike = find("05_water_strike")
    val spell_earth_strike = find("09_earth_strike")
    val spell_fire_strike = find("13_fire_strike")

    val spell_wind_bolt = find("17_wind_bolt")
    val spell_water_bolt = find("23_water_bolt")
    val spell_earth_bolt = find("29_earth_bolt")
    val spell_fire_bolt = find("35_fire_bolt")

    val spell_wind_blast = find("41_wind_blast")
    val spell_water_blast = find("47_water_blast")
    val spell_earth_blast = find("53_earth_blast")
    val spell_fire_blast = find("59_fire_blast")

    val spell_wind_wave = find("62_wind_wave")
    val spell_water_wave = find("65_water_wave")
    val spell_earth_wave = find("70_earth_wave")
    val spell_fire_wave = find("75_fire_wave")

    val spell_wind_surge = find("81_wind_surge")
    val spell_water_surge = find("85_water_surge")
    val spell_earth_surge = find("90_earth_surge")
    val spell_fire_surge = find("95_fire_surge")

    val spell_hometeleport_edgeville = find("01_zaros_home_tele")
    val spell_paddewwa_teleport = find("54_paddewwa_teleport")
    val spell_senntisten_teleport = find("60_senntisten_teleport")
    val spell_kharyllyl_teleport = find("66_kharyllyl_teleport")
    val spell_lassar_teleport = find("72_lassar_teleport")
    val spell_dareeyak_teleport = find("78_dareeyak_teleport")
    val spell_carrallagar_teleport = find("84_carrallagar_teleport")
    val spell_annakarl_teleport = find("90_annakarl_teleport")
    val spell_ghorrock_teleport = find("96_ghorrock_teleport")

    val spell_smoke_rush = find("50_smoke_rush")
    val spell_smoke_burst = find("62_smoke_burst")
    val spell_smoke_blitz = find("74_smoke_blitz")
    val spell_smoke_barrage = find("86_smoke_barrage")

    val spell_shadow_rush = find("52_shadow_rush")
    val spell_shadow_burst = find("64_shadow_burst")
    val spell_shadow_blitz = find("76_shadow_blitz")
    val spell_shadow_barrage = find("88_shadow_barrage")

    val spell_blood_rush = find("56_blood_rush")
    val spell_blood_burst = find("68_blood_burst")
    val spell_blood_blitz = find("80_blood_blitz")
    val spell_blood_barrage = find("92_blood_barrage")

    val spell_ice_rush = find("58_ice_rush")
    val spell_ice_burst = find("70_ice_burst")
    val spell_ice_blitz = find("82_ice_blitz")
    val spell_ice_barrage = find("94_ice_barrage")

    val spell_hometeleport_lunar = find("01_lunar_home_tele")
    val spell_moonclan_teleport = find("69_tele_moonclan")
    val spell_moonclan_telegroup = find("70_tele_moonclan_group")
    val spell_zmi_teleport = find("71_tele_zmialtar")
    val spell_waterbirth_teleport = find("72_tele_waterbirth")
    val spell_waterbirth_telegroup = find("73_tele_waterbirth_group")
    val spell_barboutpost_teleport = find("75_tele_barb_outpost")
    val spell_barboutpost_telegroup = find("76_tele_barb_outpost_group")
    val spell_portkhazard_teleport = find("78_tele_port_khazard")
    val spell_portkhazard_telegroup = find("79_tele_port_khazard_group")
    val spell_fishguild_teleport = find("85_tele_fish_guild")
    val spell_fishguard_telegroup = find("86_tele_fish_guild_group")
    val spell_catherby_teleport = find("87_tele_catherby")
    val spell_catherby_telegroup = find("88_tele_catherby_group")
    val spell_lunarghorrock_teleport = find("89_tele_ghorrock")
    val spell_lunarghorrock_telegroup = find("90_tele_ghorrock_group")

    val spell_bake_pie = find("65_bake_pie")
    val spell_geomancy = find("watering_can_dummy")
    val spell_cure_plant = find("66_cure_plant")
    val spell_monster_examine = find("66_monster_examine")
    val spell_npc_contact = find("67_npc_contact")
    val spell_cure_other = find("68_cure_other")
    val spell_humidify = find("68_humidify")
    val spell_cure_me = find("71_cure_me")
    val spell_hunter_kit = find("71_hunter_kit")
    val spell_cure_group = find("74_cure_group")
    val spell_stat_spy = find("75_stat_spy")
    val spell_spin_flax = find("76_spin_flax")
    val spell_superglass = find("77_superglass")
    val spell_tan_leather = find("leather")
    val spell_dream = find("79_dream")
    val spell_string_jewelry = find("80_string_jewelry")
    val spell_res_pot_share = find("81_res_pot_share")
    val spell_magic_imbue = find("82_magic_imbue")
    val spell_treat_soil = find("83_treat_soil")
    val spell_statboost_pot_share = find("84_statboost_pot_share")
    val spell_plank_make = find("86_plank_make")
    val spell_recharge_dragonstone = find("caveorb4dot")
    val spell_energy_transfer = find("91_energy_transfer")
    val spell_heal_other = find("92_heal_other")
    val spell_vengeance_other = find("93_vengeance_other")
    val spell_vengeance = find("94_vengeance")
    val spell_heal_group = find("95_heal_group")
    val spell_spellbook_swap = find("96_spellbook_swap")

    val spell_hometeleport_arceuus = find("deadman_level99_lamp")
    val spell_arceuuslibrary_teleport = find("br_mithril_platebody")
    val spell_draynormanor_teleport = find("br_mithril_platelegs")
    val spell_battlefront_teleport = find("23_teleport_battlefront")
    val spell_mindaltar_teleport = find("br_greendhide_body")
    val spell_respawn_teleport = find("poh_guide_guildtrophy")
    val spell_salvegrave_teleport = find("br_greendhide_chaps")
    val spell_fenkenstrainscastle_teleport = find("br_moonclan_body")
    val spell_westardougne_teleport = find("br_moonclan_legs")
    val spell_harmonyisland_teleport = find("br_xeric_body")
    val spell_cemetery_teleport = find("br_xeric_legs")
    val spell_barrows_teleport = find("br_air_staff")
    val spell_arceuusapeatoll_teleport = find("br_dragon_helm")

    val spell_degrime = find("placeholder_skillpethunter_black")
    val spell_resurrect_crops = find("br_swordfish")

    val spell_basic_reanimation = find("easter_helper")
    val spell_adept_reanimation = find("cert_chompy_bird_obj")
    val spell_expert_reanimation = find("evil_bob_amulet_of_manspeak")
    val spell_master_reanimation = find("magictraining_guardianstatue")

    val spell_ghostly_grasp = find("dmm_ref_hat")
    val spell_skeletal_grasp = find("dmm_ref_torso")
    val spell_undead_grasp = find("dmm_ref_legs")

    val spell_shadow_veil = find("placeholder_skillpethunter_grey")
    val spell_dark_lure = find("placeholder_snakepet_orange")
    val spell_vile_vigour = find("placeholder_snakepet_blue")

    val spell_lesser_corruption = find("zanarischoir_dummy")
    val spell_greater_corruption = find("skillcape_ardy_hood_firecape")

    val spell_mark_of_darkness = find("br_bass")
    val spell_ward_of_arceuus = find("placeholder_skillcape_ardy_hood_firecape")
    val spell_death_charge = find("placeholder_vetion_pet2")

    val spell_demonic_offering = find("placeholder_skillpethunter_gold")
    val spell_sinister_offering = find("poh_temp_limestonebrick")

    val spell_inferior_demonbane = find("br_mithril_scimitar")
    val spell_superior_demonbane = find("br_willow_bow")
    val spell_dark_demonbane = find("br_adamant_scimitar")

    val spell_resurrect_lesser_ghost = find("osb8_monkey_cow")
    val spell_resurrect_lesser_skeleton = find("osb8_monkey_bob")
    val spell_resurrect_lesser_zombie = find("osb8_monkey_donie")

    val spell_resurrect_superior_ghost = find("osb8_bamboo")
    val spell_resurrect_superior_skeleton = find("osb8_monkey_unicorn")
    val spell_resurrect_superior_zombie = find("osb8_monkey_sheep")

    val spell_resurrect_greater_ghost = find("osb8_monkey_trap")
    val spell_resurrect_greater_skeleton = find("osb8_monkey_aereck")
    val spell_resurrect_greater_zombie = find("osb8_unicorn_horn")

    val blighted_ancient_ice_sack = find("blighted_sack_icebarrage")
    val blighted_entangle_sack = find("blighted_sack_entangle")
    val blighted_teleport_spell_sack = find("blighted_sack_teleblock")
    val blighted_vengeance_sack = find("blighted_sack_vengeance")
    val blighted_surge_sack = find("blighted_sack_surge")

    val chinchoma = find("chinchompa_captured")
    val red_chinchoma = find("chinchompa_big_captured")
    val black_chinchompa = find("chinchompa_black")

    val bronze_arrow = find("bronze_arrow")
    val adamant_arrow = find("adamant_arrow")
    val rune_arrow = find("rune_arrow")
    val dragon_arrow = find("dragon_arrow")

    val runite_bolts = find("xbows_crossbow_bolts_runite")

    val avas_accumulator = find("anma_50_reward")
    val avas_assembler = find("avas_assembler")

    val shortbow = find("shortbow")
    val magic_shortbow = find("magic_shortbow")

    val dark_bow = find("darkbow")
    val dark_bow_green = find("darkbow_green")
    val dark_bow_blue = find("darkbow_blue")
    val dark_bow_yellow = find("darkbow_yellow")
    val dark_bow_white = find("darkbow_white")
    val dark_bow_bh = find("bh_darkbow_imbue")

    val armadyl_helmet = find("armadyl_helmet")
    val armadyl_chestplate = find("armadyl_chestplate")
    val armadyl_chainskirt = find("armadyl_skirt")

    val bandos_chestplate = find("bandos_chestplate")
    val bandos_tassets = find("bandos_skirt")

    val pegasian_boots = find("pegasian_boots")
    val primordial_boots = find("primordial_boots")
    val eternal_boots = find("eternal_boots")

    val berserker_ring = find("berzerker_ring")
    val archers_ring_i = find("nzone_ranger_ring")
    val seers_ring_i = find("nzone_seer_ring")
    val brimstone_ring = find("brimstone_ring")
    val ring_of_endurance = find("ring_of_endurance")

    val ultor_ring = find("ultor_ring")
    val venator_ring = find("venator_ring")
    val magus_ring = find("magus_ring")

    val amulet_of_fury = find("enchanted_onyx_amulet")
    val necklace_of_anguish = find("zenyte_necklace_enchanted")
    val occult_necklace = find("occult_necklace")
    val amulet_of_glory_4 = find("amulet_of_glory_4")
    val tormented_bracelet = find("zenyte_bracelet_enchanted")
    val regen_bracelet = find("jewl_bracelet_regen")
    val lightbearer = find("lightbearer")

    val imbued_saradomin_cape = find("ma2_saradomin_cape")
    val infinity_boots = find("magictraining_infinityboots")

    val black_dhide_body = find("black_dragonhide_body")
    val black_dhide_chaps = find("black_dragonhide_chaps")
    val snakeskin_boots = find("snakeskin_boots")
    val rune_platebody = find("rune_platebody")
    val rune_platelegs = find("rune_platelegs")
    val armadyl_godsword = find("ags")
    val dragonfire_ward = find("dragonfire_ward")
    val helm_of_neitiznot = find("fris_kingly_helm")
    val fire_cape = find("tzhaar_cape_fire")
    val infernal_cape = find("infernal_cape")
    val abyssal_whip = find("abyssal_whip")
    val fighter_torso = find("barbassault_penance_fighter_torso")
    val dragon_defender = find("dragon_parryingdagger")
    val barrows_gloves = find("hundred_gauntlets_level_10")
    val dragon_boots = find("dragon_boots")
    val rune_kiteshield = find("rune_kiteshield")
    val dragon_claws = find("dragon_claws")
    val dragon_longsword = find("dragon_longsword")
    val saradomin_blessed_sword = find("blessed_saradomin_sword")
    val crystal_shield = find("crystal_shield")

    val crystal_bow = find("crystal_bow")
    val bow_of_faerdhinen = find("bow_of_faerdhinen")
    val bow_of_faerdhinen_c_hefin = find("bow_of_faerdhinen_infinite")
    val bow_of_faerdhinen_c_ithell = find("bow_of_faerdhinen_infinite_ithell")
    val bow_of_faerdhinen_c_iorwerth = find("bow_of_faerdhinen_infinite_iorwerth")
    val bow_of_faerdhinen_c_trahaearn = find("bow_of_faerdhinen_infinite_trahaearn")
    val bow_of_faerdhinen_c_cadarn = find("bow_of_faerdhinen_infinite_cadarn")
    val bow_of_faerdhinen_c_crwys = find("bow_of_faerdhinen_infinite_crwys")
    val bow_of_faerdhinen_c_meilyr = find("bow_of_faerdhinen_infinite_meilyr")
    val bow_of_faerdhinen_c_amlodd = find("bow_of_faerdhinen_infinite_amlodd")

    val crystal_helm_hefin = find("crystal_helmet_hefin")
    val crystal_helm_ithell = find("crystal_helmet_ithell")
    val crystal_helm_iorwerth = find("crystal_helmet_iorwerth")
    val crystal_helm_trahaearn = find("crystal_helmet_trahaearn")
    val crystal_helm_cadarn = find("crystal_helmet_cadarn")
    val crystal_helm_crwys = find("crystal_helmet_crwys")
    val crystal_helm_meilyr = find("crystal_helmet")
    val crystal_helm_amlodd = find("crystal_helmet_amlodd")

    val crystal_body_hefin = find("crystal_chestplate_hefin")
    val crystal_body_ithell = find("crystal_chestplate_ithell")
    val crystal_body_iorwerth = find("crystal_chestplate_iorwerth")
    val crystal_body_trahaearn = find("crystal_chestplate_trahaearn")
    val crystal_body_cadarn = find("crystal_chestplate_cadarn")
    val crystal_body_crwys = find("crystal_chestplate_crwys")
    val crystal_body_meilyr = find("crystal_chestplate")
    val crystal_body_amlodd = find("crystal_chestplate_amlodd")

    val crystal_legs_hefin = find("crystal_platelegs_hefin")
    val crystal_legs_ithell = find("crystal_platelegs_ithell")
    val crystal_legs_iorwerth = find("crystal_platelegs_iorwerth")
    val crystal_legs_trahaearn = find("crystal_platelegs_trahaearn")
    val crystal_legs_cadarn = find("crystal_platelegs_cadarn")
    val crystal_legs_crwys = find("crystal_platelegs_crwys")
    val crystal_legs_meilyr = find("crystal_platelegs")
    val crystal_legs_amlodd = find("crystal_platelegs_amlodd")

    val soulreaper_axe = find("soulreaper")
    val amulet_of_avarice = find("wild_cave_amulet")
    val salve_amulet = find("crystalshard_necklace")
    val salve_amulet_i = find("nzone_salve_amulet")
    val salve_amulet_e = find("lotr_crystalshard_necklace_upgrade")
    val salve_amulet_ei = find("nzone_salve_amulet_e")
    val berserker_necklace = find("jewl_beserker_necklace")
    val berserker_necklace_or = find("jewl_beserker_necklace_ornament")

    val bone_dagger = find("dttd_bone_dagger")
    val bone_dagger_poison = find("dttd_bone_dagger_p")
    val bone_dagger_poison_plus = find("dttd_bone_dagger_p+")
    val bone_dagger_poison_plus_plus = find("dttd_bone_dagger_p++")
    val bone_spear = find("cave_goblin_bone_spear")
    val bone_club = find("cave_goblin_bone_club")
    val bone_crossbow = find("dttd_bone_crossbow")
    val bone_bolts = find("dttd_bone_crossbow_bolt")

    val arclight = find("arclight")
    val silverlight = find("agrith_silverlight_dyed")
    val burning_claws = find("bone_claws")
    val obsidian_helmet = find("obsidian_helmet")
    val obsidian_platebody = find("obsidian_platebody")
    val obsidian_platelegs = find("obsidian_platelegs")
    val toktz_xil_ek = find("tzhaar_knife")
    val toktz_xil_ak = find("tzhaar_splitsword")
    val tzhaar_ket_em = find("tzhaar_mace")
    val tzhaar_ket_om = find("tzhaar_maul")
    val tzhaar_ket_om_t = find("tzhaar_maul_t")
    val dragon_hunter_lance = find("dragonhunter_lance")
    val dragon_hunter_wand = find("dragonhunter_wand")
    val dragon_hunter_crossbow = find("dragonhunter_xbow")
    val dragon_hunter_crossbow_t = find("dragonhunter_xbow_vorkath")
    val dragon_hunter_crossbow_b = find("dragonhunter_xbow_kbd")
    val barronite_mace = find("barronite_mace")
    val barronite_mace_l = find("barronite_mace_trouver")
    val viggoras_chainmace = find("wild_cave_chainmace_charged")
    val ursine_chainmace = find("wild_cave_ursine_charged")
    val craws_bow = find("wild_cave_bow_charged")
    val webweaver_bow = find("wild_cave_webweaver_charged")
    val leafbladed_sword = find("leafbladed_sword")
    val leafbladed_spear = find("slayer_leafbladed_spear")
    val leafbladed_battleaxe = find("leafbladed_battleaxe")
    val colossal_blade = find("giants_foundry_colossal_blade")
    val gadderhammer = find("gadderanks_warhammer")
    val elysian_spirit_shield = find("elysian")
    val dinhs_bulwark = find("dinhs_bulwark")
    val dinhs_blazing_bulwark = find("dinhs_bulwark_ornament")
    val osmumtens_fang = find("osmumtens_fang")
    val osmumtens_fang_or = find("osmumtens_fang_ornament")
    val amulet_of_rancour = find("amulet_of_rancour")
    val radas_blessing_4 = find("zeah_blessing_elite")
    val ferocious_gloves = find("ferocious_gloves")
    val ghrazi_rapier = find("ghrazi_rapier")

    val tumekens_shadow_uncharged = find("tumekens_shadow_uncharged")
    val tumekens_shadow = find("tumekens_shadow")
    val twisted_bow = find("twisted_bow")
    val scythe_of_vitur = find("scythe_of_vitur")

    val scorching_bow = find("scorching_bow")
    val blue_moon_spear = find("frostmoon_spear")

    val bone_mace = find("rat_bone_mace")
    val bone_shortbow = find("rat_bone_bow")

    val inquisitors_great_helm = find("inquisitors_helm")
    val inquisitors_hauberk = find("inquisitors_body")
    val inquisitors_plateskirt = find("inquisitors_skirt")
    val inquisitors_mace = find("inquisitors_mace")

    val justiciar_faceguard = find("justiciar_faceguard")
    val justiciar_chestguard = find("justiciar_chestguard")
    val justiciar_legguards = find("justiciar_leg_guards")

    val torva_full_helm = find("torva_helm")
    val torva_platebody = find("torva_chest")
    val torva_platelegs = find("torva_legs")

    val virtus_mask = find("virtus_mask")
    val virtus_robe_top = find("virtus_top")
    val virtus_robe_bottom = find("virtus_legs")

    val echo_virtus_mask = find("virtus_mask_ornament")
    val echo_virtus_robe_top = find("virtus_top_ornament")
    val echo_virtus_robe_bottom = find("virtus_legs_ornament")

    val ancestral_hat = find("ancestral_hat")
    val ancestral_robe_top = find("ancestral_robe_top")
    val ancestral_robe_bottom = find("ancestral_robe_bottom")

    val keris = find("contact_keris")
    val keris_p = find("contact_keris_p")
    val keris_p_plus = find("contact_keris_p+")
    val keris_p_plus_plus = find("contact_keris_p++")
    val keris_partisan = find("keris_partisan")
    val keris_partisan_of_breaching = find("keris_partisan_breach")
    val keris_partisan_of_corruption = find("keris_partisan_corruption")
    val keris_partisan_of_the_sun = find("keris_partisan_sun")

    val void_mage_helm = find("game_pest_mage_helm")
    val void_ranger_helm = find("game_pest_archer_helm")
    val void_melee_helm = find("game_pest_melee_helm")
    val void_top = find("pest_void_knight_top")
    val void_robe = find("pest_void_knight_robes")
    val void_gloves = find("pest_void_knight_gloves")
    val elite_void_top = find("elite_void_knight_top")
    val elite_void_robe = find("elite_void_knight_robes")

    val void_mage_helm_l = find("game_pest_mage_helm_trouver")
    val void_ranger_helm_l = find("game_pest_archer_helm_trouver")
    val void_melee_helm_l = find("game_pest_melee_helm_trouver")
    val void_top_l = find("pest_void_knight_top_trouver")
    val void_robe_l = find("pest_void_knight_robes_trouver")
    val void_gloves_l = find("pest_void_knight_gloves_trouver")
    val elite_void_top_l = find("elite_void_knight_top_trouver")
    val elite_void_robe_l = find("elite_void_knight_robes_trouver")

    val void_mage_helm_or = find("league_3_void_mage_helm")
    val void_ranger_helm_or = find("league_3_void_range_helm")
    val void_melee_helm_or = find("league_3_void_melee_helm")
    val void_top_or = find("league_3_void_knight_top")
    val void_robe_or = find("league_3_void_knight_robes")
    val void_gloves_or = find("league_3_void_knight_gloves")
    val elite_void_top_or = find("league_3_void_knight_top_elite")
    val elite_void_robe_or = find("league_3_void_knight_robes_elite")

    val void_mage_helm_l_or = find("league_3_void_mage_helm_trouver")
    val void_ranger_helm_l_or = find("league_3_void_range_helm_trouver")
    val void_melee_helm_l_or = find("league_3_void_melee_helm_trouver")
    val void_top_l_or = find("league_3_void_knight_top_trouver")
    val void_robe_l_or = find("league_3_void_knight_robes_trouver")
    val void_gloves_l_or = find("league_3_void_knight_gloves_trouver")
    val elite_void_top_l_or = find("league_3_void_knight_top_elite_trouver")
    val elite_void_robe_l_or = find("league_3_void_knight_robes_elite_trouver")

    val dharoks_helm_100 = find("barrows_dharok_head_100")
    val dharoks_helm_75 = find("barrows_dharok_head_75")
    val dharoks_helm_50 = find("barrows_dharok_head_50")
    val dharoks_helm_25 = find("barrows_dharok_head_25")

    val dharoks_platebody_100 = find("barrows_dharok_body_100")
    val dharoks_platebody_75 = find("barrows_dharok_body_75")
    val dharoks_platebody_50 = find("barrows_dharok_body_50")
    val dharoks_platebody_25 = find("barrows_dharok_body_25")

    val dharoks_platelegs_100 = find("barrows_dharok_legs_100")
    val dharoks_platelegs_75 = find("barrows_dharok_legs_75")
    val dharoks_platelegs_50 = find("barrows_dharok_legs_50")
    val dharoks_platelegs_25 = find("barrows_dharok_legs_25")

    val dharoks_greataxe_100 = find("barrows_dharok_weapon_100")
    val dharoks_greataxe_75 = find("barrows_dharok_weapon_75")
    val dharoks_greataxe_50 = find("barrows_dharok_weapon_50")
    val dharoks_greataxe_25 = find("barrows_dharok_weapon_25")

    val torags_helm_100 = find("barrows_torag_head_100")
    val torags_helm_75 = find("barrows_torag_head_75")
    val torags_helm_50 = find("barrows_torag_head_50")
    val torags_helm_25 = find("barrows_torag_head_25")

    val torags_platebody_100 = find("barrows_torag_body_100")
    val torags_platebody_75 = find("barrows_torag_body_75")
    val torags_platebody_50 = find("barrows_torag_body_50")
    val torags_platebody_25 = find("barrows_torag_body_25")

    val torags_platelegs_100 = find("barrows_torag_legs_100")
    val torags_platelegs_75 = find("barrows_torag_legs_75")
    val torags_platelegs_50 = find("barrows_torag_legs_50")
    val torags_platelegs_25 = find("barrows_torag_legs_25")

    val torags_hammers_100 = find("barrows_torag_weapon_100")
    val torags_hammers_75 = find("barrows_torag_weapon_75")
    val torags_hammers_50 = find("barrows_torag_weapon_50")
    val torags_hammers_25 = find("barrows_torag_weapon_25")

    val veracs_helm_100 = find("barrows_verac_head_100")
    val veracs_helm_75 = find("barrows_verac_head_75")
    val veracs_helm_50 = find("barrows_verac_head_50")
    val veracs_helm_25 = find("barrows_verac_head_25")

    val veracs_brassard_100 = find("barrows_verac_body_100")
    val veracs_brassard_75 = find("barrows_verac_body_75")
    val veracs_brassard_50 = find("barrows_verac_body_50")
    val veracs_brassard_25 = find("barrows_verac_body_25")

    val veracs_plateskirt_100 = find("barrows_verac_legs_100")
    val veracs_plateskirt_75 = find("barrows_verac_legs_75")
    val veracs_plateskirt_50 = find("barrows_verac_legs_50")
    val veracs_plateskirt_25 = find("barrows_verac_legs_25")

    val veracs_flail_100 = find("barrows_verac_weapon_100")
    val veracs_flail_75 = find("barrows_verac_weapon_75")
    val veracs_flail_50 = find("barrows_verac_weapon_50")
    val veracs_flail_25 = find("barrows_verac_weapon_25")

    val ahrims_hood_100 = find("barrows_ahrim_head_100")
    val ahrims_hood_75 = find("barrows_ahrim_head_75")
    val ahrims_hood_50 = find("barrows_ahrim_head_50")
    val ahrims_hood_25 = find("barrows_ahrim_head_25")

    val ahrims_robetop_100 = find("barrows_ahrim_body_100")
    val ahrims_robetop_75 = find("barrows_ahrim_body_75")
    val ahrims_robetop_50 = find("barrows_ahrim_body_50")
    val ahrims_robetop_25 = find("barrows_ahrim_body_25")

    val ahrims_robeskirt_100 = find("barrows_ahrim_legs_100")
    val ahrims_robeskirt_75 = find("barrows_ahrim_legs_75")
    val ahrims_robeskirt_50 = find("barrows_ahrim_legs_50")
    val ahrims_robeskirt_25 = find("barrows_ahrim_legs_25")

    val ahrims_staff_100 = find("barrows_ahrim_weapon_100")
    val ahrims_staff_75 = find("barrows_ahrim_weapon_75")
    val ahrims_staff_50 = find("barrows_ahrim_weapon_50")
    val ahrims_staff_25 = find("barrows_ahrim_weapon_25")

    val amulet_of_the_damned_full = find("damned_amulet")

    val efaritays_aid = find("vampyre_ring")

    // ---- Smithing: metal bars ----
    val bronze_bar = find("bronze_bar")
    val iron_bar = find("iron_bar")
    val steel_bar = find("steel_bar")
    val mithril_bar = find("mithril_bar")
    val adamant_bar = find("adamantite_bar")
    val rune_bar = find("runite_bar")
    val silver_bar = find("silver_bar")
    val gold_bar = find("gold_bar")

    // ---- Smithing: ores (needed for smelting) ----
    val copper_ore = find("copper_ore")
    val tin_ore = find("tin_ore")
    val iron_ore = find("iron_ore")
    val coal = find("coal")
    val mithril_ore = find("mithril_ore")
    val adamantite_ore = find("adamantite_ore")
    val runite_ore = find("runite_ore")
    val silver_ore = find("silver_ore")
    val gold_ore = find("gold_ore")

    // ---- Smithing: bronze products ----
    val bronze_dagger = find("bronze_dagger")
    val bronze_sword = find("bronze_sword")
    val bronze_longsword = find("bronze_longsword")
    val bronze_2h_sword = find("bronze_2h_sword")
    val bronze_scimitar = find("bronze_scimitar")
    val bronze_med_helm = find("bronze_med_helm")
    val bronze_full_helm = find("bronze_full_helm")
    val bronze_chainbody = find("bronze_chainbody")
    val bronze_platelegs = find("bronze_platelegs")
    val bronze_plateskirt = find("bronze_plateskirt")
    val bronze_platebody = find("bronze_platebody")
    val bronze_sq_shield = find("bronze_sq_shield")
    val bronze_kiteshield = find("bronze_kiteshield")
    val bronze_mace = find("bronze_mace")

    // ---- Smithing: iron products ----
    val iron_dagger = find("iron_dagger")
    val iron_sword = find("iron_sword")
    val iron_longsword = find("iron_longsword")
    val iron_2h_sword = find("iron_2h_sword")
    val iron_scimitar = find("iron_scimitar")
    val iron_med_helm = find("iron_med_helm")
    val iron_full_helm = find("iron_full_helm")
    val iron_chainbody = find("iron_chainbody")
    val iron_platelegs = find("iron_platelegs")
    val iron_plateskirt = find("iron_plateskirt")
    val iron_platebody = find("iron_platebody")
    val iron_sq_shield = find("iron_sq_shield")
    val iron_kiteshield = find("iron_kiteshield")
    val iron_mace = find("iron_mace")

    // ---- Smithing: steel products ----
    val steel_dagger = find("steel_dagger")
    val steel_sword = find("steel_sword")
    val steel_longsword = find("steel_longsword")
    val steel_2h_sword = find("steel_2h_sword")
    val steel_scimitar = find("steel_scimitar")
    val steel_med_helm = find("steel_med_helm")
    val steel_full_helm = find("steel_full_helm")
    val steel_chainbody = find("steel_chainbody")
    val steel_platelegs = find("steel_platelegs")
    val steel_plateskirt = find("steel_plateskirt")
    val steel_platebody = find("steel_platebody")
    val steel_sq_shield = find("steel_sq_shield")
    val steel_kiteshield = find("steel_kiteshield")
    val steel_mace = find("steel_mace")

    // ---- Smithing: mithril products ----
    val mithril_dagger = find("mithril_dagger")
    val mithril_sword = find("mithril_sword")
    val mithril_longsword = find("mithril_longsword")
    val mithril_2h_sword = find("mithril_2h_sword")
    val mithril_scimitar = find("mithril_scimitar")
    val mithril_med_helm = find("mithril_med_helm")
    val mithril_full_helm = find("mithril_full_helm")
    val mithril_chainbody = find("mithril_chainbody")
    val mithril_platelegs = find("mithril_platelegs")
    val mithril_plateskirt = find("mithril_plateskirt")
    val mithril_platebody = find("mithril_platebody")
    val mithril_sq_shield = find("mithril_sq_shield")
    val mithril_kiteshield = find("mithril_kiteshield")
    val mithril_mace = find("mithril_mace")

    // ---- Smithing: adamant products ----
    val adamant_dagger = find("adamant_dagger")
    val adamant_sword = find("adamant_sword")
    val adamant_longsword = find("adamant_longsword")
    val adamant_2h_sword = find("adamant_2h_sword")
    val adamant_scimitar = find("adamant_scimitar")
    val adamant_med_helm = find("adamant_med_helm")
    val adamant_full_helm = find("adamant_full_helm")
    val adamant_chainbody = find("adamant_chainbody")
    val adamant_platelegs = find("adamant_platelegs")
    val adamant_plateskirt = find("adamant_plateskirt")
    val adamant_platebody = find("adamant_platebody")
    val adamant_sq_shield = find("adamant_sq_shield")
    val adamant_kiteshield = find("adamant_kiteshield")
    val adamant_mace = find("adamant_mace")

    // ---- Smithing: rune products ----
    val rune_dagger = find("rune_dagger")
    val rune_sword = find("rune_sword")
    val rune_longsword = find("rune_longsword")
    val rune_2h_sword = find("rune_2h_sword")
    val rune_scimitar = find("rune_scimitar")
    val rune_med_helm = find("rune_med_helm")
    val rune_full_helm = find("rune_full_helm")
    val rune_chainbody = find("rune_chainbody")
    // rune_platelegs already declared above (line ~847)
    val rune_plateskirt = find("rune_plateskirt")
    // rune_platebody already declared above
    val rune_sq_shield = find("rune_sq_shield")
    // rune_kiteshield already declared above
    val rune_mace = find("rune_mace")

    // ---- Fletching: bow strings, unstrung bows, arrows ----
    val bowstring = find("bowstring")
    val arrow_shaft = find("arrow_shaft")
    val headless_arrow = find("headless_arrow")

    val shortbow_u = find("shortbow_u")
    val longbow_u = find("longbow_u")
    val oak_shortbow_u = find("oak_shortbow_u")
    val oak_longbow_u = find("oak_longbow_u")
    val willow_shortbow_u = find("willow_shortbow_u")
    val willow_longbow_u = find("willow_longbow_u")
    val maple_shortbow_u = find("maple_shortbow_u")
    val maple_longbow_u = find("maple_longbow_u")
    val yew_shortbow_u = find("yew_shortbow_u")
    val yew_longbow_u = find("yew_longbow_u")
    val magic_shortbow_u = find("magic_shortbow_u")
    val magic_longbow_u = find("magic_longbow_u")

    val longbow = find("longbow")
    val oak_shortbow = find("oak_shortbow")
    val oak_longbow = find("oak_longbow")
    val willow_shortbow = find("willow_shortbow")
    val willow_longbow = find("willow_longbow")
    val maple_shortbow = find("maple_shortbow")
    val maple_longbow = find("maple_longbow")
    val yew_shortbow = find("yew_shortbow")
    val yew_longbow = find("yew_longbow")
    val magic_longbow = find("magic_longbow")

    val bronze_arrowhead = find("bronze_arrowtips")
    val iron_arrowhead = find("iron_arrowtips")
    val steel_arrowhead = find("steel_arrowtips")
    val mithril_arrowhead = find("mithril_arrowtips")
    val adamant_arrowhead = find("adamant_arrowtips")
    val rune_arrowhead = find("rune_arrowtips")

    val iron_arrow = find("iron_arrow")
    val steel_arrow = find("steel_arrow")
    val mithril_arrow = find("mithril_arrow")
    // bronze_arrow, adamant_arrow, rune_arrow already declared above

    // ---- Herblore: vials ----
    val vial_of_water = find("vial_of_water")
    val vial_empty = find("vial")

    // ---- Herblore: grimy herbs ----
    val grimy_guam = find("grimy_guam_leaf")
    val grimy_marrentill = find("grimy_marrentill")
    val grimy_tarromin = find("grimy_tarromin")
    val grimy_harralander = find("grimy_harralander")
    val grimy_ranarr_weed = find("grimy_ranarr_weed")
    val grimy_toadflax = find("grimy_toadflax")
    val grimy_irit_leaf = find("grimy_irit_leaf")
    val grimy_avantoe = find("grimy_avantoe")
    val grimy_kwuarm = find("grimy_kwuarm")
    val grimy_snapdragon = find("grimy_snapdragon")
    val grimy_cadantine = find("grimy_cadantine")
    val grimy_lantadyme = find("grimy_lantadyme")
    val grimy_dwarf_weed = find("grimy_dwarfweed")
    val grimy_torstol = find("grimy_torstol")

    // ---- Herblore: clean herbs ----
    val guam_leaf = find("guam_leaf")
    val marrentill = find("marrentill")
    val tarromin = find("tarromin")
    val harralander = find("harralander")
    val ranarr_weed = find("ranarr_weed")
    val toadflax = find("toadflax")
    val irit_leaf = find("irit_leaf")
    val avantoe = find("avantoe")
    val kwuarm = find("kwuarm")
    val snapdragon = find("snapdragon")
    val cadantine = find("cadantine")
    val lantadyme = find("lantadyme")
    val dwarf_weed = find("dwarfweed")
    val torstol = find("torstol")

    // ---- Herblore: unfinished potions ----
    val guam_potion_unf = find("guam_potion_unf")
    val marrentill_potion_unf = find("marrentill_potion_unf")
    val tarromin_potion_unf = find("tarromin_potion_unf")
    val harralander_potion_unf = find("harralander_potion_unf")
    val ranarr_potion_unf = find("ranarr_potion_unf")
    val toadflax_potion_unf = find("toadflax_potion_unf")
    val irit_potion_unf = find("irit_potion_unf")
    val avantoe_potion_unf = find("avantoe_potion_unf")
    val kwuarm_potion_unf = find("kwuarm_potion_unf")
    val snapdragon_potion_unf = find("snapdragon_potion_unf")
    val cadantine_potion_unf = find("cadantine_potion_unf")
    val lantadyme_potion_unf = find("lantadyme_potion_unf")
    val dwarf_weed_potion_unf = find("dwarfweed_potion_unf")
    val torstol_potion_unf = find("torstol_potion_unf")

    // ---- Herblore: secondary ingredients ----
    val eye_of_newt = find("eye_of_newt")
    val unicorn_horn_dust = find("unicorn_horn_dust")
    val limpwurt_root = find("limpwurt_root")
    val red_spider_eggs = find("red_spider_eggs")
    val snape_grass = find("snape_grass")
    val toad_legs = find("swamp_toad_legs")
    val irit_leaf_secondary = find("irit_leaf") // same obj, used as secondary for super-antipoison
    val white_berries = find("white_berries")
    val mort_myre_fungus = find("mort_myre_fungus")
    val wine_of_zamorak = find("wine_of_zamorak")
    val jangerberries = find("jangerberries")
    val dragon_scale_dust = find("dragon_scale_dust")
    val potato_cactus = find("potato_cactus")
    val crushed_nest = find("birds_nest_crushed")
    val ground_mud_rune = find("mud_rune_ground")
    val crushed_superior_dragon_bones = find("dragon_bones_superior_ground")

    // ---- Herblore: finished potions (dose 3) ----
    val attack_potion_3 = find("attack_potion_3")
    val antipoison_3 = find("antipoison_3")
    val strength_potion_3 = find("strength_potion_3")
    val restore_potion_3 = find("restore_potion_3")
    val agility_potion_3 = find("agility_potion_3")
    val energy_potion_3 = find("energy_potion_3")
    val defence_potion_3 = find("defence_potion_3")
    val prayer_potion_3 = find("prayer_potion_3")
    val super_attack_3 = find("super_attack_3")
    val super_antipoison_3 = find("superantipoison_3")
    val fishing_potion_3 = find("fishing_potion_3")
    val super_energy_3 = find("super_energy_3")
    val hunter_potion_3 = find("hunter_potion_3")
    val super_strength_3 = find("super_strength_3")
    val super_restore_3 = find("super_restore_3")
    val super_defence_3 = find("super_defence_3")
    val antifire_3 = find("antifire_potion_3")
    val ranging_potion_3 = find("ranging_potion_3")
    val magic_potion_3 = find("magic_potion_3")
    val zamorak_brew_3 = find("zamorak_brew_3")
    val combat_potion_3 = find("combat_potion_3")
    val bastion_potion_3 = find("bastion_potion_3")
    val battlemage_potion_3 = find("battlemage_potion_3")
    val antidote_plus_3 = find("antidote_plus_3")
    val extended_antifire_3 = find("antifire_potion_extended_3")
    val saradomin_brew_3 = find("saradomin_brew_3")

    val woodcutting_icon = find("tree_icon_dummy", 2122627481130992920)
    val bank_icon = find("bank_icon_dummy", 7806876055985215263)
    val furnace_icon = find("furnace_icon_dummy", 937693285129466531)
    val mining_icon = find("mining_tutor_icon_dummy", 1887266795659978258)
    val smithing_icon = find("smithing_tutor_icon_dummy", 5958751754372942517)
}
