@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.spot.SpotanimReferences

typealias spotanims = BaseSpotanims

object BaseSpotanims : SpotanimReferences() {
    val osb8_skillcape_banana_spotanim = find("osb8_skillcape_banana_spotanim")
    val smokepuff = find("smokepuff")
    val sp_attackglow_red = find("sp_attackglow_red")

    val hw07_arm_from_the_ground_spotanim = find("hw07_arm_from_the_ground_spotanim")
    val skillcape_diary_spotanim = find("skillcape_diary_spotanim")
    val trollromance_heart = find("trollromance_heart")
    val poh_absorb_tablet_magic = find("poh_absorb_tablet_magic")
    val emote_lightbulb_spot = find("emote_lightbulb_spot")
    val emote_duststamp_spot = find("emote_duststamp_spot")
    val skillcapes_fletching_bow_spotanim = find("skillcapes_fletching_bow_spotanim")
    val skillcapes_magic_spotanim = find("skillcapes_magic_spotanim")
    val skillcapes_mining_spotanim = find("skillcapes_mining_spotanim")
    val skillcapes_smithing_spotanim = find("skillcapes_smithing_spotanim")
    val skillcapes_quest_cape_spotanim = find("skillcapes_quest_cape_spotanim")
    val skillcapes_runecrafting_spotanim = find("skillcapes_runecrafting_spotanim")
    val skillcapes_crafting_spotanim = find("skillcapes_crafting_spotanim")
    val skillcapes_fishing_spotanim = find("skillcapes_fishing_spotanim")
    val skillcapes_construction_spotanim = find("skillcapes_construction_spotanim")
    val skillcapes_cooking_spotanim = find("skillcapes_cooking_spotanim")
    val skillcapes_woodcutting_spotanim = find("skillcapes_woodcutting_spotanim")
    val skillcape_attack_spotanim = find("skillcape_attack_spotanim")
    val skillcape_defend_spotanim = find("skillcape_defend_spotanim")
    val skillcape_farming_spotanim = find("skillcape_farming_spotanim")
    val skillcape_thieving_spotanim = find("skillcape_thieving_spotanim")
    val skillcape_slayer_spotanim = find("skillcape_slayer_spotanim")
    val skillcapes_strength = find("skillcapes_strength")
    val skillcapes_prayer = find("skillcapes_prayer")
    val skillcapes_agility = find("skillcapes_agility")
    val skillcapes_firemaking = find("skillcapes_firemaking")
    val skillcapes_range = find("skillcapes_range")
    val skillcapes_hitpoints = find("skillcapes_hitpoints")
    val skillcapes_herblore = find("skillcapes_herblore")
    val skillcapes_hunting = find("skillcapes_hunting")
    val air_guitar_spotanim = find("air_guitar_spotanim")
    val max_cape = find("max_cape")
    val briefcase_spotanim = find("briefcase_spotanim")
    val dinhs_bulwark_glow_idle = find("dinhs_bulwark_glow_idle")
    val premier_club_emote_spotanim_bronze = find("premier_club_emote_spotanim_bronze")
    val premier_club_emote_spotanim_silver = find("premier_club_emote_spotanim_silver")
    val premier_club_emote_spotanim_gold = find("premier_club_emote_spotanim_gold")
    val league_twisted_relic_unlock_spot = find("league_twisted_relic_unlock_spot")
    val league_trailblazer_relic_unlock_spot = find("league_trailblazer_relic_unlock_spot")
    val fx_emote_party01_active = find("fx_emote_party01_active")
    val hw23_emote_bat_spotanim = find("hw23_emote_bat_spotanim")

    val ballista_special = find("ballista_special")

    val darkbow_dragon_head_flying_projanim = find("darkbow_dragon_head_flying_projanim")
    val darkbow_dragon_head_flying_impact_anim = find("darkbow_dragon_head_flying_impact_anim")
    val darkbow_generic_smoke_arrow_flight = find("darkbow_generic_smoke_arrow_flight")
    val darkbow_smoke_arrow_impact = find("darkbow_smoke_arrow_impact")

    val stunned = find("stunned")
    val failedspell_impact = find("failedspell_impact")

    val windstrike_casting = find("windstrike_casting")
    val windstrike_travel = find("windstrike_travel")
    val windstrike_impact = find("windstrike_impact")
    val waterstrike_casting = find("waterstrike_casting")
    val waterstrike_travel = find("waterstrike_travel")
    val waterstrike_impact = find("waterstrike_impact")
    val earthstrike_casting = find("earthstrike_casting")
    val earthstrike_travel = find("earthstrike_travel")
    val earthstrike_impact = find("earthstrike_impact")
    val firestrike_casting = find("firestrike_casting")
    val firestrike_travel = find("firestrike_travel")
    val firestrike_impact = find("firestrike_impact")

    val windbolt_casting = find("windbolt_casting")
    val windbolt_travel = find("windbolt_travel")
    val windbolt_impact = find("windbolt_impact")
    val waterbolt_casting = find("waterbolt_casting")
    val waterbolt_travel = find("waterbolt_travel")
    val waterbolt_impact = find("waterbolt_impact")
    val earthbolt_casting = find("earthbolt_casting")
    val earthbolt_travel = find("earthbolt_travel")
    val earthbolt_impact = find("earthbolt_impact")
    val firebolt_casting = find("firebolt_casting")
    val firebolt_travel = find("firebolt_travel")
    val firebolt_impact = find("firebolt_impact")

    val fireblast_casting = find("fireblast_casting")
    val fireblast_travel = find("fireblast_travel")
    val fireblast_impact = find("fireblast_impact")
    val windblast_casting = find("windblast_casting")
    val windblast_travel = find("windblast_travel")
    val windblast_impact = find("windblast_impact")
    val waterblast_casting = find("waterblast_casting")
    val waterblast_travel = find("waterblast_travel")
    val waterblast_impact = find("waterblast_impact")
    val earthblast_casting = find("earthblast_casting")
    val earthblast_travel = find("earthblast_travel")
    val earthblast_impact = find("earthblast_impact")

    val firewave_casting = find("firewave_casting")
    val firewave_travel = find("firewave_travel")
    val firewave_impact = find("firewave_impact")
    val windwave_casting = find("windwave_casting")
    val windwave_travel = find("windwave_travel")
    val windwave_impact = find("windwave_impact")
    val waterwave_casting = find("waterwave_casting")
    val waterwave_travel = find("waterwave_travel")
    val waterwave_impact = find("waterwave_impact")
    val earthwave_casting = find("earthwave_casting")
    val earthwave_travel = find("earthwave_travel")
    val earthwave_impact = find("earthwave_impact")

    val windsurge_casting = find("windsurge_casting")
    val windsurge_travel = find("windsurge_travel")
    val windsurge_impact = find("windsurge_impact")
    val watersurge_casting = find("watersurge_casting")
    val watersurge_travel = find("watersurge_travel")
    val watersurge_impact = find("watersurge_impact")
    val earthsurge_casting = find("earthsurge_casting")
    val earthsurge_travel = find("earthsurge_travel")
    val earthsurge_impact = find("earthsurge_impact")
    val firesurge_casting = find("firesurge_casting")
    val firesurge_travel = find("firesurge_travel")
    val firesurge_impact = find("firesurge_impact")

    val tumekens_shadow_casting = find("tumekens_shadow_casting")
    val tumekens_shadow_travel = find("tumekens_shadow_travel")
    val tumekens_shadow_impact = find("tumekens_shadow_impact")
}
