@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.obj.ObjReferences

typealias objs = BaseObjs

object BaseObjs : ObjReferences() {
    val template_for_cert = find("template_for_cert")
    val template_for_transform = find("template_for_transform")
    val template_for_placeholder = find("template_for_placeholder")
    val null_item_placeholder = find("blankobject")
    val nothing_ = find("blankobject")

    val coins = find("coins")
    val platinum_tokens = find("platinum")

    val ashes = find("ashes")
    val vile_ashes = find("vile_ashes")

    val bronze_spear = find("bronze_spear")
    val bronze_bolts = find("bronze_bolts")
    val cow_hide = find("cow_hide")
    val raw_beef = find("raw_beef")
    val raw_chicken = find("raw_chicken")
    val raw_rat_meat = find("raw_rat_meat")
    val giant_key = find("giant_key")

    // ---- Bones ----
    val bones = find("bones")
    val big_bones = find("big_bones")
    val burnt_bones = find("bones_burnt")
    val bat_bones = find("bat_bones")
    val wolf_bones = find("wolf_bones")
    val babydragon_bones = find("babydragon_bones")
    val dragon_bones = find("dragon_bones")
    val wyvern_bones = find("wyvern_bones")
    val wyrm_bones = find("wyrm_bones")
    val drake_bones = find("drake_bones")
    val hydra_bones = find("hydra_bones")
    val lava_dragon_bones = find("lava_dragon_bones")
    val dagannoth_bones = find("dagannoth_king_bones")
    val superior_dragon_bones = find("dragon_bones_superior")
    val jogre_bones = find("tbwt_jogre_bones")
    val zogre_bones = find("zogre_bones")
    val fayrg_bones = find("zogre_ancestral_bones_fayg")
    val raurg_bones = find("zogre_ancestral_bones_raurg")
    val ourg_bones = find("zogre_ancestral_bones_ourg")
    val snowball = find("gublinch_snowball")

    // ---- Tools & General Items ----
    val pot_empty = find("pot_empty")
    val jug_empty = find("jug_empty")
    val shears = find("shears")
    val knife = find("knife")
    val bucket_empty = find("bucket_empty")
    val bucket_milk = find("bucket_milk")
    val bowl_empty = find("bowl_empty")

    /* Compatibility aliases for renamed milk */
    val bucket_of_milk
        get() = bucket_milk

    val cake_tin = find("cake_tin")
    val chefs_hat = find("chefs_hat")
    val tinderbox = find("tinderbox")
    val chisel = find("chisel")
    val spade = find("spade")
    val hammer = find("hammer")
    val newcomer_map = find("newcomer_map")
    val wool = find("wool")
    val ball_of_wool = find("ball_of_wool")
    val rope = find("rope")
    val flier = find("flier")
    val gold_bar = find("gold_bar")
    val regen_bracelet = find("jewl_bracelet_regen")
    val guthix_staff_rune = find("guthix_staff")
    val shrimp = find("shrimp")
    val raw_herring = find("raw_herring")
    val herring = find("herring")
    val beer = find("beer")
    val steel_scimitar = find("steel_scimitar")
    val mithril_chainbody = find("mithril_chainbody")
    val iron_battleaxe = find("iron_battleaxe")
    val steel_battleaxe = find("steel_battleaxe")
    val mithril_battleaxe = find("mithril_battleaxe")
    val iron_sword = find("iron_sword")
    val iron_full_helm = find("iron_full_helm")
    val steel_med_helm = find("steel_med_helm")
    val iron_dagger = find("iron_dagger")
    val iron_med_helm = find("iron_med_helm")
    val iron_kiteshield = find("iron_kiteshield")
    val bronze_pickaxe = find("bronze_pickaxe")
    val uncut_sapphire = find("uncut_sapphire")
    val uncut_emerald = find("uncut_emerald")
    val uncut_ruby = find("uncut_ruby")
    val uncut_diamond = find("uncut_diamond")
    val bronze_mace = find("bronze_mace")
    val bronze_sword = find("bronze_sword")
    val bronze_med_helm = find("bronze_med_helm")
    val bronze_scimitar = find("bronze_scimitar")
    val rune_longsword = find("rune_longsword")
    val adamant_platebody = find("adamant_platebody")
    val adamant_kiteshield = find("adamant_kiteshield")
    val silver_ore = find("silver_ore")
    val rune_chainbody = find("rune_chainbody")
    val rune_sq_shield = find("rune_sq_shield")
    val rune_2h_sword = find("rune_2h_sword")
    val steel_full_helm = find("steel_full_helm")
    val mithril_sq_shield = find("mithril_sq_shield")
    val rune_med_helm = find("rune_med_helm")
    val gold_ore = find("gold_ore")
    val steel_kiteshield = find("steel_kiteshield")
    val steel_bar = find("steel_bar")
    val coal = find("coal")
    val bronze_sq_shield = find("bronze_sq_shield")
    val sos_security_book = find("sos_security_book")
    val pack_jug_empty = find("pack_jug_empty")
    val pack_bucket = find("pack_bucket")

    // Icons
    val bank_icon_dummy = find("bank_icon_dummy")
    val furnace_icon_dummy = find("furnace_icon_dummy")
    val mining_site_icon_dummy = find("mining_site_icon_dummy")
    val woodcutting_tutor_icon_dummy = find("woodcutting_tutor_icon_dummy")
    val smithing_tutor_icon_dummy = find("smithing_tutor_icon_dummy")

    /* Compatibility aliases for misc items */
    val bank_icon
        get() = bank_icon_dummy

    val furnace_icon
        get() = furnace_icon_dummy

    val mining_icon
        get() = mining_site_icon_dummy

    val woodcutting_icon
        get() = woodcutting_tutor_icon_dummy

    val smithing_icon
        get() = smithing_tutor_icon_dummy

    val shrimps
        get() = shrimp

    val bobs_axe_flyer
        get() = flier

    val grimy_guam = find("grimy_guam")
    val grimy_marrentill = find("grimy_marrentill")
    val grimy_tarromin = find("grimy_tarromin")
    val grimy_harralander = find("grimy_harralander")
    val grimy_ranarr_weed = find("grimy_ranarr_weed")
    val grimy_toadflax = find("unidentified_toadflax")
    val tin_ore = find("tin_ore")
    val cowhide = find("cowhide")
    val iron_ore = find("iron_ore")
    val grimy_irit_leaf = find("grimy_irit_leaf")
    val grimy_avantoe = find("grimy_avantoe")
    val grimy_kwuarm = find("grimy_kwuarm")
    val grimy_snapdragon = find("unidentified_snapdragon")
    val grimy_cadantine = find("grimy_cadantine")
    val grimy_lantadyme = find("grimy_lantadyme")
    val grimy_dwarf_weed = find("grimy_dwarf_weed")
    val grimy_torstol = find("unidentified_torstol")
    val clean_guam = find("guam_leaf")
    val clean_marrentill = find("marentill")
    val clean_tarromin = find("tarromin")
    val clean_harralander = find("harralander")
    val clean_ranarr = find("ranarr_weed")
    val clean_toadflax = find("toadflax")
    val clean_irit = find("irit_leaf")
    val clean_avantoe = find("avantoe")
    val clean_kwuarm = find("kwuarm")
    val clean_snapdragon = find("snapdragon")
    val clean_cadantine = find("cadantine")
    val clean_lantadyme = find("lantadyme")
    val clean_dwarf_weed = find("dwarf_weed")
    val clean_torstol = find("torstol")
    val guam_potion_unf = find("guamvial")
    val marrentill_potion_unf = find("marrentillvial")
    val tarromin_potion_unf = find("tarrominvial")
    val harralander_potion_unf = find("harralandervial")
    val ranarr_potion_unf = find("ranarrvial")
    val toadflax_potion_unf = find("toadflaxvial")
    val irit_potion_unf = find("iritvial")
    val avantoe_potion_unf = find("avantoevial")
    val kwuarm_potion_unf = find("kwuarmvial")
    val snapdragon_potion_unf = find("snapdragonvial")
    val cadantine_potion_unf = find("cadantinevial")
    val lantadyme_potion_unf = find("lantadymevial")
    val dwarf_weed_potion_unf = find("dwarfweedvial")
    val torstol_potion_unf = find("torstolvial")
    val vial_of_water = find("vial_water")
    val eye_of_newt = find("eye_of_newt")
    val unicorn_horn_dust = find("unicorn_horn_dust")
    val limpwurt_root = find("limpwurt_root")
    val red_spider_eggs = find("red_spiders_eggs")
    val white_berries = find("white_berries")
    val snape_grass = find("snape_grass")
    val mort_myre_fungus = find("mortmyremushroom")
    val dragon_scale_dust = find("dragon_scale_dust")
    val wine_of_zamorak = find("wine_of_zamorak")
    val potato_cactus = find("cactus_potato")
    val jangerberries = find("jangerberries")
    val crushed_nest = find("crushed_bird_nest")
    val attack_potion_3 = find("3dose1attack")
    val antipoison_3 = find("3doseantipoison")
    val strength_potion_3 = find("3dose1strength")
    val restore_potion_3 = find("3dosestatrestore")
    val defence_potion_3 = find("3dose1defense")
    val prayer_potion_3 = find("3doseprayerrestore")
    val super_attack_3 = find("3dose2attack")
    val super_antipoison_3 = find("3dose2antipoison")
    val fishing_potion_3 = find("3dosefisherspotion")
    val super_energy_3 = find("3dose2energy")
    val super_strength_3 = find("3dose2strength")
    val super_restore_3 = find("3dose2restore")
    val super_defence_3 = find("3dose2defense")
    val antifire_3 = find("3dose1antidragon")
    val ranging_potion_3 = find("3doserangerspotion")
    val magic_potion_3 = find("3dose1magic")
    val zamorak_brew_3 = find("3dosepotionofzamorak")
    val saradomin_brew_3 = find("3dosepotionofsaradomin")
    val copper_ore = find("copper_ore")
    val raw_tuna = find("raw_tuna")
    val dragon_harpoon = find("dragon_harpoon")
    val dragon_harpoon_or = find("placeholder_dragon_harpoon")
    val infernal_harpoon = find("infernal_harpoon")
    val infernal_harpoon_or = find("placeholder_infernal_harpoon")
    val infernal_harpoon_or_uncharged = find("infernal_harpoon_empty")
    val crystal_harpoon = find("crystal_harpoon")
    val dragon_pickaxe = find("dragon_pickaxe")
    val dragon_pickaxe_or_zalcano = find("zalcano_pickaxe")
    val dragon_pickaxe_or_trailblazer = find("trailblazer_pickaxe")
    val dragon_pickaxe_upgraded = find("dragon_pickaxe_upgrade_kit")
    val infernal_pickaxe = find("infernal_pickaxe")
    val infernal_pickaxe_uncharged = find("infernal_pickaxe_empty")
    val infernal_pickaxe_or = find("placeholder_infernal_pickaxe")
    val infernal_pickaxe_or_uncharged = find("infernal_pickaxe_empty")
    val third_age_pickaxe = find("3a_pickaxe")
    val crystal_pickaxe = find("crystal_pickaxe")
    val dragon_longsword = find("dragon_longsword")
    val darkbow = find("darkbow")
    val darkbow_green = find("darkbow_green")
    val darkbow_blue = find("darkbow_blue")
    val darkbow_yellow = find("darkbow_yellow")
    val darkbow_white = find("darkbow_white")
    val darkbow_bh = find("br_darkbow")

    /* Compatibility aliases for renamed items */
    val dark_bow: org.rsmod.game.type.obj.ObjType
        get() = darkbow

    val dark_bow_green: org.rsmod.game.type.obj.ObjType
        get() = darkbow_green

    val dark_bow_blue: org.rsmod.game.type.obj.ObjType
        get() = darkbow_blue

    val dark_bow_yellow: org.rsmod.game.type.obj.ObjType
        get() = darkbow_yellow

    val dark_bow_white: org.rsmod.game.type.obj.ObjType
        get() = darkbow_white

    val dark_bow_bh: org.rsmod.game.type.obj.ObjType
        get() = darkbow_bh

    val `3a_pickaxe`
        get() = third_age_pickaxe

    // ---- Logs ----
    val logs = find("logs")
    val oak_logs = find("oak_logs")
    val willow_logs = find("willow_logs")
    val maple_logs = find("maple_logs")
    val yew_logs = find("yew_logs")
    val magic_logs = find("magic_logs")
    val redwood_logs = find("redwood_logs")
    val teak_logs = find("teak_logs")
    val mahogany_logs = find("mahogany_logs")

    // ---- Skillcapes ----
    val attack_skillcape = find("skillcape_attack")
    val attack_skillcape_t = find("skillcape_attack_trimmed")
    val attack_hood = find("skillcape_attack_hood")
    val strength_skillcape = find("skillcape_strength")
    val strength_skillcape_t = find("skillcape_strength_trimmed")
    val strength_hood = find("skillcape_strength_hood")
    val defence_skillcape = find("skillcape_defence")
    val defence_skillcape_t = find("skillcape_defence_trimmed")
    val defence_hood = find("skillcape_defence_hood")
    val hitpoints_skillcape = find("skillcape_hitpoints")
    val hitpoints_skillcape_t = find("skillcape_hitpoints_trimmed")
    val hitpoints_hood = find("skillcape_hitpoints_hood")
    val ranged_skillcape = find("skillcape_ranging")
    val ranged_skillcape_t = find("skillcape_ranging_trimmed")
    val ranged_hood = find("skillcape_ranging_hood")
    val prayer_skillcape = find("skillcape_prayer")
    val prayer_skillcape_t = find("skillcape_prayer_trimmed")
    val prayer_hood = find("skillcape_prayer_hood")
    val magic_skillcape = find("skillcape_magic")
    val magic_skillcape_t = find("skillcape_magic_trimmed")
    val magic_hood = find("skillcape_magic_hood")
    val cooking_skillcape = find("skillcape_cooking")
    val cooking_skillcape_t = find("skillcape_cooking_trimmed")
    val cooking_hood = find("skillcape_cooking_hood")
    val woodcutting_skillcape = find("skillcape_woodcutting")
    val woodcutting_skillcape_t = find("skillcape_woodcutting_trimmed")
    val woodcutting_hood = find("skillcape_woodcutting_hood")
    val fletching_skillcape = find("skillcape_fletching")
    val fletching_skillcape_t = find("skillcape_fletching_trimmed")
    val fletching_hood = find("skillcape_fletching_hood")
    val fishing_skillcape = find("skillcape_fishing")
    val fishing_skillcape_t = find("skillcape_fishing_trimmed")
    val fishing_hood = find("skillcape_fishing_hood")
    val firemaking_skillcape = find("skillcape_firemaking")
    val firemaking_skillcape_t = find("skillcape_firemaking_trimmed")
    val firemaking_hood = find("skillcape_firemaking_hood")
    val crafting_skillcape = find("skillcape_crafting")
    val crafting_skillcape_t = find("skillcape_crafting_trimmed")
    val crafting_hood = find("skillcape_crafting_hood")
    val smithing_skillcape = find("skillcape_smithing")
    val smithing_skillcape_t = find("skillcape_smithing_trimmed")
    val smithing_hood = find("skillcape_smithing_hood")
    val mining_skillcape = find("skillcape_mining")
    val mining_skillcape_t = find("skillcape_mining_trimmed")
    val mining_hood = find("skillcape_mining_hood")
    val herblore_skillcape = find("skillcape_herblore")
    val herblore_skillcape_t = find("skillcape_herblore_trimmed")
    val herblore_hood = find("skillcape_herblore_hood")
    val agility_skillcape = find("skillcape_agility")
    val agility_skillcape_t = find("skillcape_agility_trimmed")
    val agility_hood = find("skillcape_agility_hood")
    val thieving_skillcape = find("skillcape_thieving")
    val thieving_skillcape_t = find("skillcape_thieving_trimmed")
    val thieving_hood = find("skillcape_thieving_hood")
    val slayer_skillcape = find("skillcape_slayer")
    val slayer_skillcape_t = find("skillcape_slayer_trimmed")
    val slayer_hood = find("skillcape_slayer_hood")
    val farming_skillcape = find("skillcape_farming")
    val farming_skillcape_t = find("skillcape_farming_trimmed")
    val farming_hood = find("skillcape_farming_hood")
    val quest_point_cape = find("skillcape_qp")
    val quest_point_cape_t = find("skillcape_qp_trimmed")
    val quest_point_hood = find("skillcape_qp_hood")
    val achievement_diary_cape = find("skillcape_ad")
    val achievement_diary_cape_t = find("skillcape_ad_trimmed")
    val achievement_diary_hood = find("skillcape_ad_hood")
    val runecrafting_skillcape = find("skillcape_runecrafting")
    val runecrafting_skillcape_t = find("skillcape_runecrafting_trimmed")
    val runecrafting_hood = find("skillcape_runecrafting_hood")
    val hunter_skillcape = find("skillcape_hunting")
    val hunter_skillcape_t = find("skillcape_hunting_trimmed")
    val hunter_hood = find("skillcape_hunting_hood")
    val construction_skillcape = find("skillcape_construction")
    val construction_skillcape_t = find("skillcape_construction_trimmed")
    val construction_hood = find("skillcape_construction_hood")

    // ---- Max Capes ----
    val max_hood = find("skillcape_max_hood")
    val max_cape_worn = find("skillcape_max_worn")
    val max_cape_inv = find("skillcape_max")

    // ---- Graceful (Vanilla) ----
    val graceful_hood = find("graceful_hood")
    val graceful_hood_worn = find("graceful_hood_worn")
    val graceful_cape = find("graceful_cape")
    val graceful_cape_worn = find("graceful_cape_worn")
    val graceful_top = find("graceful_top")
    val graceful_top_worn = find("graceful_top_worn")
    val graceful_legs = find("graceful_legs")
    val graceful_legs_worn = find("graceful_legs_worn")
    val graceful_gloves = find("graceful_gloves")
    val graceful_gloves_worn = find("graceful_gloves_worn")
    val graceful_boots = find("graceful_boots")
    val graceful_boots_worn = find("graceful_boots_worn")

    // ---- Graceful (Colored) ----
    val arceuus_graceful_hood_inv = find("zeah_graceful_hood_arceuus")
    val arceuus_graceful_hood_worn = find("zeah_graceful_hood_arceuus_worn")
    val arceuus_graceful_cape_inv = find("zeah_graceful_cape_arceuus")
    val arceuus_graceful_cape_worn = find("zeah_graceful_cape_arceuus_worn")
    val arceuus_graceful_top_inv = find("zeah_graceful_top_arceuus")
    val arceuus_graceful_top_worn = find("zeah_graceful_top_arceuus_worn")
    val arceuus_graceful_legs_inv = find("zeah_graceful_legs_arceuus")
    val arceuus_graceful_legs_worn = find("zeah_graceful_legs_arceuus_worn")
    val arceuus_graceful_gloves_inv = find("zeah_graceful_gloves_arceuus")
    val arceuus_graceful_gloves_worn = find("zeah_graceful_gloves_arceuus_worn")
    val arceuus_graceful_boots_inv = find("zeah_graceful_boots_arceuus")
    val arceuus_graceful_boots_worn = find("zeah_graceful_boots_arceuus_worn")

    val piscarilius_graceful_hood_inv = find("zeah_graceful_hood_piscarilius")
    val piscarilius_graceful_hood_worn = find("zeah_graceful_hood_piscarilius_worn")
    val piscarilius_graceful_cape_inv = find("zeah_graceful_cape_piscarilius")
    val piscarilius_graceful_cape_worn = find("zeah_graceful_cape_piscarilius_worn")
    val piscarilius_graceful_top_inv = find("zeah_graceful_top_piscarilius")
    val piscarilius_graceful_top_worn = find("zeah_graceful_top_piscarilius_worn")
    val piscarilius_graceful_legs_inv = find("zeah_graceful_legs_piscarilius")
    val piscarilius_graceful_legs_worn = find("zeah_graceful_legs_piscarilius_worn")
    val piscarilius_graceful_gloves_inv = find("zeah_graceful_gloves_piscarilius")
    val piscarilius_graceful_gloves_worn = find("zeah_graceful_gloves_piscarilius_worn")
    val piscarilius_graceful_boots_inv = find("zeah_graceful_boots_piscarilius")
    val piscarilius_graceful_boots_worn = find("zeah_graceful_boots_piscarilius_worn")

    val lovakengj_graceful_hood_inv = find("zeah_graceful_hood_lovakengj")
    val lovakengj_graceful_hood_worn = find("zeah_graceful_hood_lovakengj_worn")
    val lovakengj_graceful_cape_inv = find("zeah_graceful_cape_lovakengj")
    val lovakengj_graceful_cape_worn = find("zeah_graceful_cape_lovakengj_worn")
    val lovakengj_graceful_top_inv = find("zeah_graceful_top_lovakengj")
    val lovakengj_graceful_top_worn = find("zeah_graceful_top_lovakengj_worn")
    val lovakengj_graceful_legs_inv = find("zeah_graceful_legs_lovakengj")
    val lovakengj_graceful_legs_worn = find("zeah_graceful_legs_lovakengj_worn")
    val lovakengj_graceful_gloves_inv = find("zeah_graceful_gloves_lovakengj")
    val lovakengj_graceful_gloves_worn = find("zeah_graceful_gloves_lovakengj_worn")
    val lovakengj_graceful_boots_inv = find("zeah_graceful_boots_lovakengj")
    val lovakengj_graceful_boots_worn = find("zeah_graceful_boots_lovakengj_worn")

    val shayzien_graceful_hood_inv = find("zeah_graceful_hood_shayzien")
    val shayzien_graceful_hood_worn = find("zeah_graceful_hood_shayzien_worn")
    val shayzien_graceful_cape_inv = find("zeah_graceful_cape_shayzien")
    val shayzien_graceful_cape_worn = find("zeah_graceful_cape_shayzien_worn")
    val shayzien_graceful_top_inv = find("zeah_graceful_top_shayzien")
    val shayzien_graceful_top_worn = find("zeah_graceful_top_shayzien_worn")
    val shayzien_graceful_legs_inv = find("zeah_graceful_legs_shayzien")
    val shayzien_graceful_legs_worn = find("zeah_graceful_legs_shayzien_worn")
    val shayzien_graceful_gloves_inv = find("zeah_graceful_gloves_shayzien")
    val shayzien_graceful_gloves_worn = find("zeah_graceful_gloves_shayzien_worn")
    val shayzien_graceful_boots_inv = find("zeah_graceful_boots_shayzien")
    val shayzien_graceful_boots_worn = find("zeah_graceful_boots_shayzien_worn")

    val hosidius_graceful_hood_inv = find("zeah_graceful_hood_hosidius")
    val hosidius_graceful_hood_worn = find("zeah_graceful_hood_hosidius_worn")
    val hosidius_graceful_cape_inv = find("zeah_graceful_cape_hosidius")
    val hosidius_graceful_cape_worn = find("zeah_graceful_cape_hosidius_worn")
    val hosidius_graceful_top_inv = find("zeah_graceful_top_hosidius")
    val hosidius_graceful_top_worn = find("zeah_graceful_top_hosidius_worn")
    val hosidius_graceful_legs_inv = find("zeah_graceful_legs_hosidius")
    val hosidius_graceful_legs_worn = find("zeah_graceful_legs_hosidius_worn")
    val hosidius_graceful_gloves_inv = find("zeah_graceful_gloves_hosidius")
    val hosidius_graceful_gloves_worn = find("zeah_graceful_gloves_hosidius_worn")
    val hosidius_graceful_boots_inv = find("zeah_graceful_boots_hosidius")
    val hosidius_graceful_boots_worn = find("zeah_graceful_boots_hosidius_worn")

    val kourend_graceful_hood_inv = find("zeah_graceful_hood_kourend")
    val kourend_graceful_hood_worn = find("zeah_graceful_hood_kourend_worn")
    val kourend_graceful_cape_inv = find("zeah_graceful_cape_kourend")
    val kourend_graceful_cape_worn = find("zeah_graceful_cape_kourend_worn")
    val kourend_graceful_top_inv = find("zeah_graceful_top_kourend")
    val kourend_graceful_top_worn = find("zeah_graceful_top_kourend_worn")
    val kourend_graceful_legs_inv = find("zeah_graceful_legs_kourend")
    val kourend_graceful_legs_worn = find("zeah_graceful_legs_kourend_worn")
    val kourend_graceful_gloves_inv = find("zeah_graceful_gloves_kourend")
    val kourend_graceful_gloves_worn = find("zeah_graceful_gloves_kourend_worn")
    val kourend_graceful_boots_inv = find("zeah_graceful_boots_kourend")
    val kourend_graceful_boots_worn = find("zeah_graceful_boots_kourend_worn")

    // ---- Barrows (Ahrim) ----
    val ahrims_hood_100 = find("barrows_ahrim_head_100")
    val ahrims_hood_75 = find("barrows_ahrim_head_75")
    val ahrims_hood_50 = find("barrows_ahrim_head_50")
    val ahrims_hood_25 = find("barrows_ahrim_head_25")
    val ahrims_robetop_100 = find("barrows_ahrim_body_100")
    val ahrims_robetop_75 = find("barrows_ahrim_body_75")
    val ahrims_robetop_50 = find("barrows_ahrim_body_50")
    val ahrims_robetop_25 = find("barrows_ahrim_body_25")
    val ahrims_robeskirt_100 = find("barrows_ahrim_legs_100")
    val ahrims_robeskirt_75 = find("barrows_ahrim_legs_75")
    val ahrims_robeskirt_50 = find("barrows_ahrim_legs_50")
    val ahrims_robeskirt_25 = find("barrows_ahrim_legs_25")
    val ahrims_staff_100 = find("barrows_ahrim_weapon_100")
    val ahrims_staff_75 = find("barrows_ahrim_weapon_75")
    val ahrims_staff_50 = find("barrows_ahrim_weapon_50")
    val ahrims_staff_25 = find("barrows_ahrim_weapon_25")

    // ---- Barrows (Dharok) ----
    val dharoks_helm_100 = find("barrows_dharok_head_100")
    val dharoks_helm_75 = find("barrows_dharok_head_75")
    val dharoks_helm_50 = find("barrows_dharok_head_50")
    val dharoks_helm_25 = find("barrows_dharok_head_25")
    val dharoks_platebody_100 = find("barrows_dharok_body_100")
    val dharoks_platebody_75 = find("barrows_dharok_body_75")
    val dharoks_platebody_50 = find("barrows_dharok_body_50")
    val dharoks_platebody_25 = find("barrows_dharok_body_25")
    val dharoks_platelegs_100 = find("barrows_dharok_legs_100")
    val dharoks_platelegs_75 = find("barrows_dharok_legs_75")
    val dharoks_platelegs_50 = find("barrows_dharok_legs_50")
    val dharoks_platelegs_25 = find("barrows_dharok_legs_25")
    val dharoks_greataxe_100 = find("barrows_dharok_weapon_100")
    val dharoks_greataxe_75 = find("barrows_dharok_weapon_75")
    val dharoks_greataxe_50 = find("barrows_dharok_weapon_50")
    val dharoks_greataxe_25 = find("barrows_dharok_weapon_25")

    // ---- Barrows (Torag) ----
    val torags_helm_100 = find("barrows_torag_head_100")
    val torags_helm_75 = find("barrows_torag_head_75")
    val torags_helm_50 = find("barrows_torag_head_50")
    val torags_helm_25 = find("barrows_torag_head_25")
    val torags_platebody_100 = find("barrows_torag_body_100")
    val torags_platebody_75 = find("barrows_torag_body_75")
    val torags_platebody_50 = find("barrows_torag_body_50")
    val torags_platebody_25 = find("barrows_torag_body_25")
    val torags_platelegs_100 = find("barrows_torag_legs_100")
    val torags_platelegs_75 = find("barrows_torag_legs_75")
    val torags_platelegs_50 = find("barrows_torag_legs_50")
    val torags_platelegs_25 = find("barrows_torag_legs_25")
    val torags_hammers_100 = find("barrows_torag_weapon_100")
    val torags_hammers_75 = find("barrows_torag_weapon_75")
    val torags_hammers_50 = find("barrows_torag_weapon_50")
    val torags_hammers_25 = find("barrows_torag_weapon_25")

    // ---- Pouches ----
    val rcu_pouch_small = find("rcu_pouch_small")
    val rcu_pouch_medium = find("rcu_pouch_medium")
    val rcu_pouch_medium_degrade = find("rcu_pouch_medium_degrade")
    val rcu_pouch_large = find("rcu_pouch_large")
    val rcu_pouch_large_degrade = find("rcu_pouch_large_degrade")
    val rcu_pouch_giant = find("rcu_pouch_giant")
    val rcu_pouch_giant_degrade = find("rcu_pouch_giant_degrade")
    val rcu_pouch_colossal = find("rcu_pouch_colossal")
    val rcu_pouch_colossal_degrade = find("rcu_pouch_colossal_degrade")
    val coal_bag = find("coal_bag")
    val coal_bag_open = find("coal_bag_open")
    // Canonical names (match obj.sym for validator compatibility)
    val airrune = find("airrune")
    val waterrune = find("waterrune")
    val earthrune = find("earthrune")
    val firerune = find("firerune")
    val mindrune = find("mindrune")
    val bodyrune = find("bodyrune")
    val chaosrune = find("chaosrune")
    val deathrune = find("deathrune")
    val naturerune = find("naturerune")
    val lawrune = find("lawrune")
    val cosmicrune = find("cosmicrune")
    val bloodrune = find("bloodrune")
    val soulrune = find("soulrune")
    val astralrune = find("astralrune")

    // Underscore aliases for backward compatibility
    val air_rune
        get() = airrune

    val water_rune
        get() = waterrune

    val earth_rune
        get() = earthrune

    val fire_rune
        get() = firerune

    val mind_rune
        get() = mindrune

    val body_rune
        get() = bodyrune

    val chaos_rune
        get() = chaosrune

    val death_rune
        get() = deathrune

    val nature_rune
        get() = naturerune

    val law_rune
        get() = lawrune

    val cosmic_rune
        get() = cosmicrune

    val blood_rune
        get() = bloodrune

    val soul_rune
        get() = soulrune

    val astral_rune
        get() = astralrune

    val air_rune_nz = find("nzone_airrune")
    val water_rune_nz = find("nzone_waterrune")
    val earth_rune_nz = find("nzone_earthrune")
    val fire_rune_nz = find("nzone_firerune")
    val chaos_rune_nz = find("nzone_chaosrune")
    val death_rune_nz = find("nzone_deathrune")
    val blood_rune_nz = find("nzone_bloodrune")
    val sunfire_rune = find("sunfirerune")
    val mist_rune = find("mistrune")
    val dust_rune = find("dustrune")
    val mud_rune = find("mudrune")
    val smoke_rune = find("smokerune")
    val steam_rune = find("steamrune")
    val lava_rune = find("lavarune")

    // ---- Magic Weapons ----
    val staff_of_the_dead = find("sotd")
    val toxic_staff_of_the_dead = find("toxic_sotd")
    val staff_of_light = find("staff_of_light")
    val staff_of_balance = find("staff_of_balance")
    val saradomin_staff = find("saradomin_staff")
    val guthix_staff = find("guthix_staff")
    val zamorak_staff = find("zamorak_staff")
    val smoke_battlestaff = find("smoke_battlestaff")
    val mystic_smoke_staff = find("mystic_smoke_battlestaff")
    val ibans_staff = find("ibanstaff")
    val ibans_staff_u = find("ibanstaff_upgraded")
    val toxic_staff_uncharged = find("toxic_sotd")
    val slayers_staff = find("slayer_staff")
    val slayers_staff_e = find("slayer_staff_enchanted")
    val thammarons_sceptre = find("wild_cave_sceptre_uncharged")
    val thammarons_sceptre_a = find("wild_cave_sceptre_charged")
    val thammarons_sceptre_au = find("wild_cave_sceptre_uncharged")
    val accursed_sceptre = find("wild_cave_accursed_uncharged")
    val accursed_sceptre_a = find("wild_cave_accursed_charged")
    val accursed_sceptre_au = find("wild_cave_accursed_uncharged")
    val void_knight_mace = find("pest_void_knight_mace")
    val void_knight_mace_l = find("pest_void_knight_mace_trouver")

    // ---- Special & Missing Content ----
    val chinchompa = find("chinchompa_captured")
    val red_chinchompa = find("chinchompa_big_captured")
    val black_chinchompa = find("chinchompa_black")
    val bone_dagger = find("dttd_bone_dagger")
    val bone_dagger_poison = find("dttd_bone_dagger_p")
    val bone_dagger_poison_plus = find("dttd_bone_dagger_p+")
    val bone_dagger_poison_plus_plus = find("dttd_bone_dagger_p++")
    val bone_spear = find("cave_goblin_bone_spear")
    val bone_club = find("cave_goblin_bone_club")
    val bone_crossbow = find("dttd_bone_crossbow")
    val bone_bolts = find("dttd_bone_crossbow_bolt")
    val soulreaper_axe = find("soulreaper")
    val twisted_bow = find("twisted_bow")
    val dragon_hunter_crossbow = find("dragon_hunter_crossbow")
    val dragon_hunter_lance = find("dragon_hunter_crossbow")
    val dragon_hunter_wand = find("dragon_hunter_crossbow")
    val arclight = find("arclight")
    val burning_claws = find("dragon_claws")
    val silverlight = find("silverlight")
    val toktz_xil_ek = find("tzhaar_knife")
    val toktz_xil_ak = find("tzhaar_splitsword")
    val tzhaar_ket_em = find("tzhaar_mace")
    val tzhaar_ket_om = find("tzhaar_maul")
    val tzhaar_ket_om_t = find("tzhaar_maul_t")
    val keris = find("contact_keris")
    val keris_p = find("contact_keris_p")
    val keris_p_plus = find("contact_keris_p+")
    val keris_p_plus_plus = find("contact_keris_p++")
    val keris_partisan = find("keris_partisan")
    val keris_partisan_of_breaching = find("keris_partisan_breach")
    val keris_partisan_of_corruption = find("keris_partisan_corruption")
    val keris_partisan_of_the_sun = find("keris_partisan_sun")
    val barronite_mace = find("barronite_mace")
    val barronite_mace_l = find("barronite_mace_trouver")
    val viggoras_chainmace = find("wild_cave_chainmace_charged")
    val ursine_chainmace = find("wild_cave_ursine_charged")
    val leafbladed_sword = find("leafbladed_sword")
    val leafbladed_spear = find("slayer_leafbladed_spear")
    val leafbladed_battleaxe = find("leafbladed_battleaxe")
    val colossal_blade = find("giants_foundry_colossal_blade")
    val bone_mace = find("rat_bone_mace")
    val inquisitors_mace = find("inquisitors_mace")
    val osmumtens_fang = find("osmumtens_fang")
    val osmumtens_fang_or = find("osmumtens_fang_ornament")
    val gadderhammer = find("gadderanks_warhammer")
    val inquisitors_great_helm = find("inquisitors_helm")
    val inquisitors_hauberk = find("inquisitors_body")
    val inquisitors_plateskirt = find("inquisitors_skirt")
    val berserker_necklace = find("jewl_beserker_necklace")
    val berserker_necklace_or = find("jewl_beserker_necklace_ornament")
    val craws_bow = find("wild_cave_bow_charged")
    val webweaver_bow = find("wild_cave_webweaver_charged")
    val scorching_bow = find("scorching_bow")
    val bone_shortbow = find("rat_bone_bow")
    val elysian_spirit_shield = find("elysian")
    val skull_sceptre_i = find("sos_skull_sceptre_imbued")
    val karamja_rum = find("karamjarum")
    val piratemessage = find("piratemessage")
    val chest_key = find("chest_key")
    val bowstring = find("bow_string")
    val arrow_shaft = find("arrow_shaft")
    val feather = find("feather")
    val headless_arrow = find("headless_arrow")
    val shortbow_u = find("unstrung_shortbow")
    val longbow_u = find("unstrung_longbow")
    val oak_shortbow_u = find("unstrung_oak_shortbow")
    val oak_longbow_u = find("unstrung_oak_longbow")
    val willow_shortbow_u = find("unstrung_willow_shortbow")
    val willow_longbow_u = find("unstrung_willow_longbow")
    val maple_shortbow_u = find("unstrung_maple_shortbow")
    val maple_longbow_u = find("unstrung_maple_longbow")
    val yew_shortbow_u = find("unstrung_yew_shortbow")
    val yew_longbow_u = find("unstrung_yew_longbow")
    val magic_shortbow_u = find("unstrung_magic_shortbow")
    val magic_longbow_u = find("unstrung_magic_longbow")
    val shortbow = find("shortbow")
    val longbow = find("longbow")
    val oak_shortbow = find("oak_shortbow")
    val oak_longbow = find("oak_longbow")
    val willow_shortbow = find("willow_shortbow")
    val willow_longbow = find("willow_longbow")
    val maple_shortbow = find("maple_shortbow")
    val maple_longbow = find("maple_longbow")
    val yew_shortbow = find("yew_shortbow")
    val yew_longbow = find("yew_longbow")
    val magic_shortbow = find("magic_shortbow")
    val magic_longbow = find("magic_longbow")
    val bronze_arrowhead = find("bronze_arrowheads")
    val iron_arrowhead = find("iron_arrowheads")
    val steel_arrowhead = find("steel_arrowheads")
    val mithril_arrowhead = find("mithril_arrowheads")
    val adamant_arrowhead = find("adamant_arrowheads")
    val rune_arrowhead = find("rune_arrowheads")
    val bronze_arrow = find("bronze_arrow")
    val iron_arrow = find("iron_arrow")
    val steel_arrow = find("steel_arrow")
    val mithril_arrow = find("mithril_arrow")
    val adamant_arrow = find("adamant_arrow")
    val rune_arrow = find("rune_arrow")
    val bronze_bolts_u = find("xbows_crossbow_bolts_bronze_unfeathered")
    val iron_bolts_u = find("xbows_crossbow_bolts_iron_unfeathered")
    val steel_bolts_u = find("xbows_crossbow_bolts_steel_unfeathered")
    val mithril_bolts_u = find("xbows_crossbow_bolts_mithril_unfeathered")
    val adamant_bolts_u = find("xbows_crossbow_bolts_adamantite_unfeathered")
    val rune_bolts_u = find("xbows_crossbow_bolts_runite_unfeathered")
    val iron_bolts = find("xbows_crossbow_bolts_iron")
    val steel_bolts = find("xbows_crossbow_bolts_steel")
    val mithril_bolts = find("xbows_crossbow_bolts_mithril")
    val adamant_bolts = find("xbows_crossbow_bolts_adamantite")
    val rune_bolts = find("xbows_crossbow_bolts_runite")
    val bronze_axe = find("bronze_axe")
    val iron_axe = find("iron_axe")
    val steel_axe = find("steel_axe")
    val black_axe = find("black_axe")
    val mithril_axe = find("mithril_axe")
    val adamant_axe = find("adamant_axe")
    val rune_axe = find("rune_axe")
    val gilded_axe = find("trail_gilded_axe")
    val dragon_axe = find("dragon_axe")
    val dragon_axe_or = find("placeholder_dragon_axe")
    val third_age_axe = find("3a_axe")
    val infernal_axe = find("infernal_axe")
    val infernal_axe_or = find("placeholder_infernal_axe")
    val crystal_axe = find("crystal_axe")

    /* Compatibility aliases for renamed axes */
    val `3a_axe`
        get() = third_age_axe

    val small_fishing_net = find("net")
    val grain = find("grain")
    val pot_of_flour = find("osb9_cookout_pot_of_flour")
    val egg = find("egg")
    val cabbage_seed = find("cabbage_seed")
    val cabbage = find("cabbage")
    val onion = find("onion")
    val potato = find("potato")
    val raw_shrimp = find("raw_shrimp")
    val achey_tree_logs = find("achey_tree_logs")
    val arctic_pine_logs = find("arctic_pine_logs_pyre")
    val blisterwood_logs = find("blisterwood_logs")
    val music_cape = find("music_cape")
    val music_cape_t = find("music_cape_trimmed")
    val amulet_of_avarice = find("amulet_of_power")
    val salve_amulet = find("nzone_salve_amulet")
    val salve_amulet_e = find("nzone_salve_amulet_e")
    val salve_amulet_i = find("nzone_salve_amulet")
    val salve_amulet_ei = find("nzone_salve_amulet_e")
    val efaritays_aid = find("burgh_efaritay_info_scroll")

    // ---- Spells (Combat) ----
    val spell_wind_strike = find("01_wind_strike")
    val spell_water_strike = find("05_water_strike")
    val spell_earth_strike = find("09_earth_strike")
    val spell_fire_strike = find("13_fire_strike")
    val spell_wind_bolt = find("17_wind_bolt")
    val spell_water_bolt = find("23_water_bolt")
    val spell_earth_bolt = find("29_earth_bolt")
    val spell_fire_bolt = find("35_fire_bolt")
    val spell_wind_blast = find("41_wind_blast")
    val spell_water_blast = find("47_water_blast")
    val spell_earth_blast = find("53_earth_blast")
    val spell_fire_blast = find("59_fire_blast")
    val spell_wind_wave = find("62_wind_wave")
    val spell_water_wave = find("65_water_wave")
    val spell_earth_wave = find("70_earth_wave")
    val spell_fire_wave = find("75_fire_wave")
    val spell_wind_surge = find("81_wind_surge")
    val spell_water_surge = find("85_water_surge")
    val spell_earth_surge = find("90_earth_surge")
    val spell_fire_surge = find("95_fire_surge")

    // ---- Spells (Utility) ----
    val spell_bind = find("20_bind")
    val spell_snare = find("50_snare")
    val spell_entangle = find("79_entangle")
    val spell_tele_block = find("85_teleport_block")
    val spell_teleport_to_target = find("85_teleport_block")
    val spell_monster_examine = find("66_monster_examine")
    val spell_cure_other = find("68_cure_other")
    val spell_cure_me = find("71_cure_me")
    val spell_crumble_undead = find("39_crumble_undead")
    val spell_iban_blast = find("50_iban_blast")
    val spell_claws_of_guthix = find("60_claws_of_guthix")
    val spell_flames_of_zamorak = find("60_flames_of_zamorak")
    val spell_saradomin_strike = find("60_saradomin_strike")
    val spell_magic_dart = find("50_magic_dart")
    val spell_ice_rush = find("58_ice_rush")
    val spell_ice_burst = find("70_ice_burst")
    val spell_blood_blitz = find("80_blood_blitz")
    val spell_ice_blitz = find("82_ice_blitz")
    val spell_blood_barrage = find("92_blood_barrage")
    val spell_ice_barrage = find("94_ice_barrage")
    val spell_vengeance_other = find("93_vengeance_other")
    val spell_vengeance = find("94_vengeance")

    // ---- PvP/LMS Rune Packs ----
    val lms_rune_pouch = find("bh_rune_pouch")
    val rune_pouch = find("bh_rune_pouch")
    val rune_pouch_l = find("bh_rune_pouch_trouver")
    val divine_rune_pouch = find("divine_rune_pouch")
    val divine_rune_pouch_l = find("divine_rune_pouch_trouver")
    val blighted_ancient_ice_sack = find("blighted_sack_icebarrage")
    val blighted_entangle_sack = find("blighted_sack_entangle")
    val blighted_teleport_spell_sack = find("blighted_sack_teleblock")
    val blighted_vengeance_sack = find("blighted_sack_vengeance")
    val blighted_surge_sack = find("blighted_sack_surge")

    // ---- Justiciar ----
    val justiciar_faceguard = find("justiciar_faceguard")
    val justiciar_chestguard = find("justiciar_chestguard")
    val justiciar_legguards = find("justiciar_leg_guards")
    val chaos_gauntlets = find("gauntlets_of_chaos")
    val devils_element = find("devils_element")
    val tome_of_water = find("tome_of_water")
    val tome_of_earth = find("tome_of_earth")
    val tome_of_fire = find("tome_of_fire")
    val bryophytas_staff = find("bryophyta_staff")
    val purging_staff = find("purging_staff")
    val amulet_of_the_damned_full = find("damned_amulet")
    val amulet_of_the_damned_degraded = find("damned_amulet_degraded")
    val brimstone_ring = find("brimstone_ring")

    // ---- Unique Stubs (To avoid Duplicate Key crashes) ----
    val twinflame_staff = find("blankobject")
    val dragon_hunter_crossbow_t = find("blankobject")
    val dragon_hunter_crossbow_b = find("blankobject")
    val spell_inferior_demonbane = find("blankobject")
    val spell_superior_demonbane = find("blankobject")
    val spell_dark_demonbane = find("blankobject")
}
