package org.rsmod.tools.symbol.codegen

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.main
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.types.path
import java.nio.file.Files
import java.nio.file.Path
import java.util.TreeMap
import kotlin.io.path.nameWithoutExtension

class SymbolCodegen : CliktCommand() {
    private val symbolsDir by option("--symbols-dir").path(mustExist = true, canBeFile = false).required()
    private val outputDir by option("--output-dir").path(canBeFile = false).required()
    private val packageName by option("--package").default("org.rsmod.api.config.refs")

    override fun run() {
        Files.createDirectories(outputDir)
        
        val symFiles = Files.list(symbolsDir)
            .filter { it.toString().endsWith(".sym") }
            .toList()

        for (rootSymFile in symFiles) {
            val typeName = rootSymFile.nameWithoutExtension
            val localSymFile = symbolsDir.resolve(".local").resolve("$typeName.sym")
            
            val symbols = parseSymFiles(rootSymFile, localSymFile)
            if (symbols.isEmpty()) continue

            generateKotlinFile(typeName, symbols)
        }
    }

    private fun parseSymFiles(root: Path, local: Path): Map<String, Int> {
        val symbols = TreeMap<String, Int>()
        
        fun parseFile(path: Path) {
            if (!Files.exists(path)) return
            Files.readAllLines(path).forEach { line ->
                val trimmed = line.trim()
                if (trimmed.isEmpty() || trimmed.startsWith("#")) return@forEach
                val parts = trimmed.split(Regex("\\s+"))
                if (parts.size >= 2) {
                    val id = parts[0].toIntOrNull() ?: return@forEach
                    val name = parts[1]
                    
                    // BANNED: blankobject causing boot crashes
                    if (name == "blankobject") return@forEach
                    
                    symbols[name] = id
                }
            }
        }

        parseFile(root)
        parseFile(local)
        
        return symbols
    }

    private fun generateKotlinFile(typeName: String, symbols: Map<String, Int>) {
        val className = "Base${typeName.replaceFirstChar { it.uppercase() }}s"
        val baseClassName = getBaseClassName(typeName)
        val typeClassName = getTypeClassName(typeName)
        val fileName = "$className.kt"
        val outputFile = outputDir.resolve(fileName)
        
        val content = StringBuilder()
        content.append("@file:Suppress(\"SpellCheckingInspection\", \"unused\")\n\n")
        content.append("package $packageName\n\n")
        
        val importPackage = getBaseClassPackage(typeName)
        content.append("import $importPackage.$baseClassName\n\n")
        
        content.append("typealias ${typeName.lowercase()}s = $className\n\n")
        
        content.append("/**\n")
        content.append(" * AUTO-GENERATED SYMBOL BINDINGS. DO NOT EDIT MANUALLY.\n")
        content.append(" * This file is generated by the `generateSymbols` Gradle task.\n")
        content.append(" */\n")
        content.append("public object $className : $baseClassName() {\n")
        
        for ((name, _) in symbols) {
            val propertyName = sanitizePropertyName(name)
            content.append("    public val $propertyName: org.rsmod.game.type.${typeName.lowercase()}.$typeClassName = find(\"$name\")\n")
        }
        
        content.append("}\n")
        
        Files.writeString(outputFile, content.toString())
        echo("Generated $outputFile (${symbols.size} symbols)")
    }

    private fun getBaseClassName(typeName: String): String {
        return when (typeName.lowercase()) {
            "obj" -> "ObjReferences"
            "interf" -> "InterfReferences"
            "interface" -> "InterfReferences"
            else -> "${typeName.replaceFirstChar { it.uppercase() }}References"
        }
    }

    private fun getTypeClassName(typeName: String): String {
        return when (typeName.lowercase()) {
            "obj" -> "ObjType"
            "interface" -> "InterfaceType"
            "interf" -> "InterfaceType"
            else -> "${typeName.replaceFirstChar { it.uppercase() }}Type"
        }
    }

    private fun getBaseClassPackage(typeName: String): String {
        val subPackage = when (typeName.lowercase()) {
            "obj" -> "obj"
            "npc" -> "npc"
            "loc" -> "loc"
            "inv" -> "inv"
            "varp" -> "varp"
            "varbit" -> "varbit"
            "enum" -> "enums"
            "struct" -> "struct"
            "param" -> "param"
            "seq" -> "seq"
            "spotanim" -> "spot"
            "interface" -> "interf"
            "interf" -> "interf"
            else -> typeName.lowercase()
        }
        return "org.rsmod.api.type.refs.$subPackage"
    }

    private fun sanitizePropertyName(name: String): String {
        if (name.isEmpty()) return "_"
        
        var sanitized = name.replace(Regex("[^a-zA-Z0-9_]"), "_")
        
        if (sanitized[0].isDigit()) {
            sanitized = "_$sanitized"
        }
        
        if (isKotlinKeyword(sanitized)) {
            sanitized = "_$sanitized"
        }
        
        return sanitized
    }

    private fun isKotlinKeyword(name: String): Boolean {
        return name in setOf(
            "as", "as?", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "!in",
            "is", "!is", "null", "object", "package", "return", "super", "this", "throw", "true", "try", "typealias",
            "typeof", "val", "var", "when", "while"
        )
    }
}

fun main(args: Array<String>) = SymbolCodegen().main(args)
