package org.rsmod.api.spells.configs

import org.rsmod.api.config.refs.params
import org.rsmod.api.type.editors.obj.ObjEditor
import org.rsmod.game.type.obj.HashedObjType
import org.rsmod.map.CoordGrid

internal object SpellObjEditor : ObjEditor() {
    init {
        // Temporarily disabled: a large subset of symbolic spell obj names in this editor do not
        // resolve against current rev233 symbols, which causes invalid cache overlays and client
        // hash mismatch crashes in rsprox (notably archive 12/89 and 12/920).
        //
        // Re-enable once symbols are normalized to canonical cache names.
        //
        // Minimal stability fix: some utility spell objs exist outside the spellbook enums and may
        // be missing `spell_castxp` in the base cache. Strict boot requires it.
        spell("48_home_teleport", 0.0)
    }

    private fun editStandardSpells() {
        spell("view_jewellery_enchantment_spells", 0.0)
        spell("spell_hometeleport_lumbridge", 0.0)
        spell("spell_wind_strike", 5.5)
        spell("spell_confuse", 13.0)
        spell("view_bolt_enchantment_spells", 0.0)
        spell("spell_water_strike", 7.5)
        spell("spell_enchant_lvl_1", 17.5)
        spell("spell_earth_strike", 9.5)
        spell("spell_weaken", 21.0)
        spell("spell_fire_strike", 11.5)
        spell("spell_bones_to_bananas", 25.0)
        spell("spell_wind_bolt", 13.5)
        spell("spell_curse", 29.0)
        spell("spell_bind", 30.0)
        spell("spell_low_alchemy", 31.0)
        spell("spell_water_bolt", 16.5)
        tele("spell_varrock_teleport", 35.0, CoordGrid(0, 50, 53, 13, 32))
        spell("spell_enchant_lvl_2", 37.0)
        spell("spell_earth_bolt", 19.5)
        tele("spell_lumbridge_teleport", 41.0, CoordGrid(0, 50, 50, 21, 18))
        spell("spell_tele_grab", 43.0)
        spell("spell_fire_bolt", 22.5)
        tele("spell_falador_teleport", 47.0, CoordGrid(0, 46, 52, 21, 50))
        spell("spell_crumble_undead", 24.5)
        spell("spell_poh_teleport", 30.0)
        spell("spell_wind_blast", 25.5)
        spell("spell_monster_inspect", 30.5)
        spell("spell_superheat", 53.0)
        tele("spell_camelot_teleport", 55.5, CoordGrid(0, 43, 54, 5, 22))
        spell("spell_water_blast", 28.5)
        tele("spell_kourendcastle_teleport", 58.0, CoordGrid(0, 25, 57, 41, 25))
        spell("spell_enchant_lvl_3", 59.0)
        spell("spell_iban_blast", 30.0)
        spell("spell_snare", 60.0)
        spell("spell_magic_dart", 30.0)
        tele("spell_ardougne_teleport", 61.0, CoordGrid(0, 41, 51, 37, 38))
        spell("spell_earth_blast", 31.5)
        tele("spell_civitas_fortis_teleport", 64.0, CoordGrid(0, 26, 48, 17, 61))
        spell("spell_high_alchemy", 65.0)
        spell("spell_chargeorb_water", 56.0)
        spell("spell_enchant_lvl_4", 67.0)
        tele("spell_watchtower_teleport", 68.0, CoordGrid(0, 45, 73, 53, 40))
        spell("spell_fire_blast", 34.5)
        spell("spell_chargeorb_earth", 70.0)
        spell("spell_bones_to_peaches", 35.5)
        spell("spell_saradomin_strike", 35.0)
        spell("spell_flames_of_zamorak", 35.0)
        spell("spell_claws_of_guthix", 35.0)
        tele("spell_trollheim_teleport", 68.0, CoordGrid(0, 45, 57, 10, 31))
        spell("spell_wind_wave", 36.0)
        spell("spell_chargeorb_fire", 73.0)
        tele("spell_apeatoll_teleport", 74.0, CoordGrid(0, 43, 43, 45, 46))
        spell("spell_water_wave", 37.5)
        spell("spell_chargeorb_air", 76.0)
        spell("spell_vulnerability", 76.0)
        spell("spell_enchant_lvl_5", 78.0)
        spell("spell_earth_wave", 40.0)
        spell("spell_enfeeble", 83.0)
        spell("spell_teleother_lumbridge", 84.0)
        spell("spell_fire_wave", 42.5)
        spell("spell_entangle", 89.0)
        spell("spell_stun", 90.0)
        spell("spell_charge", 180.0)
        spell("spell_wind_surge", 44.5)
        spell("spell_teleother_falador", 92.0)
        spell("spell_water_surge", 46.5)
        spell("spell_tele_block", 80.0)
        spell("spell_teleport_to_target", 45.0)
        spell("spell_enchant_lvl_6", 97.0)
        spell("spell_teleother_camelot", 100.0)
        spell("spell_earth_surge", 48.5)
        spell("spell_enchant_lvl_7", 110.0)
        spell("spell_fire_surge", 50.5)
    }

    private fun editAncientSpells() {
        spell("spell_hometeleport_edgeville", 0.0)
        spell("spell_smoke_rush", 30.0)
        spell("spell_shadow_rush", 31.0)
        tele("spell_paddewwa_teleport", 64.0, CoordGrid(0, 48, 154, 26, 26))
        spell("spell_blood_rush", 33.0)
        spell("spell_ice_rush", 34.0)
        tele("spell_senntisten_teleport", 70.0, CoordGrid(0, 51, 52, 57, 8))
        spell("spell_smoke_burst", 36.0)
        spell("spell_shadow_burst", 37.0)
        tele("spell_kharyllyl_teleport", 76.0, CoordGrid(0, 54, 54, 38, 17))
        spell("spell_blood_burst", 39.0)
        spell("spell_ice_burst", 40.0)
        tele("spell_lassar_teleport", 82.0, CoordGrid(0, 46, 54, 60, 14))
        spell("spell_smoke_blitz", 42.0)
        spell("spell_shadow_blitz", 43.0)
        tele("spell_dareeyak_teleport", 88.0, CoordGrid(0, 46, 57, 24, 48))
        spell("spell_blood_blitz", 45.0)
        spell("spell_ice_blitz", 46.0)
        tele("spell_carrallagar_teleport", 94.0, CoordGrid(0, 49, 57, 22, 18))
        spell("spell_smoke_barrage", 48.0)
        spell("spell_shadow_barrage", 48.0)
        tele("spell_annakarl_teleport", 100.0, CoordGrid(0, 51, 60, 24, 46))
        spell("spell_blood_barrage", 51.0)
        spell("spell_ice_barrage", 52.0)
        tele("spell_ghorrock_teleport", 106.0, CoordGrid(0, 46, 60, 32, 32))
    }

    private fun editLunarSpells() {
        spell("spell_hometeleport_lunar", 0.0)
        spell("spell_bake_pie", 60.0)
        spell("spell_geomancy", 60.0)
        spell("spell_cure_plant", 87.0)
        spell("spell_monster_examine", 61.0)
        spell("spell_npc_contact", 63.0)
        spell("spell_cure_other", 65.0)
        spell("spell_humidify", 65.0)
        tele("spell_moonclan_teleport", 66.0, CoordGrid(0, 33, 61, 2, 11))
        spell("spell_moonclan_telegroup", 67.0)
        spell("spell_cure_me", 69.0)
        tele("spell_zmi_teleport", 69.0, CoordGrid(0, 38, 50, 36, 46))
        spell("spell_hunter_kit", 70.0)
        tele("spell_waterbirth_teleport", 71.0, CoordGrid(0, 39, 58, 50, 44))
        spell("spell_waterbirth_telegroup", 72.0)
        spell("spell_cure_group", 74.0)
        spell("spell_stat_spy", 76.0)
        tele("spell_barboutpost_teleport", 76.0, CoordGrid(0, 39, 55, 47, 49))
        spell("spell_barboutpost_telegroup", 77.0)
        spell("spell_spin_flax", 75.0)
        spell("spell_superglass", 78.0)
        spell("spell_tan_leather", 81.0)
        tele("spell_portkhazard_teleport", 80.0, CoordGrid(0, 41, 49, 12, 31))
        spell("spell_portkhazard_telegroup", 81.0)
        spell("spell_dream", 82.0)
        spell("spell_string_jewelry", 83.0)
        spell("spell_res_pot_share", 84.0)
        spell("spell_magic_imbue", 86.0)
        spell("spell_treat_soil", 87.0)
        spell("spell_statboost_pot_share", 88.0)
        tele("spell_fishguild_teleport", 89.0, CoordGrid(0, 40, 52, 51, 63))
        spell("spell_fishguard_telegroup", 90.0)
        spell("spell_plank_make", 90.0)
        tele("spell_catherby_teleport", 92.0, CoordGrid(0, 43, 53, 49, 57))
        spell("spell_catherby_telegroup", 93.0)
        spell("spell_recharge_dragonstone", 97.5)
        tele("spell_lunarghorrock_teleport", 96.0, CoordGrid(0, 46, 61, 30, 34))
        spell("spell_lunarghorrock_telegroup", 99.0)
        spell("spell_energy_transfer", 100.0)
        spell("spell_heal_other", 101.0)
        spell("spell_vengeance_other", 108.0)
        spell("spell_vengeance", 112.0)
        spell("spell_heal_group", 124.0)
        spell("spell_spellbook_swap", 130.0)
    }

    private fun editArceuusSpells() {
        spell("spell_hometeleport_arceuus", 0.0)
        tele("spell_arceuuslibrary_teleport", 10.0, CoordGrid(0, 25, 59, 33, 62))
        spell("spell_basic_reanimation", 32.0)
        tele("spell_draynormanor_teleport", 16.0, CoordGrid(0, 48, 52, 36, 23))
        tele("spell_battlefront_teleport", 19.0, CoordGrid(0, 21, 58, 4, 27))
        tele("spell_mindaltar_teleport", 22.0, CoordGrid(0, 46, 54, 36, 53))
        spell("spell_respawn_teleport", 27.0)
        spell("spell_ghostly_grasp", 22.5)
        spell("spell_resurrect_lesser_ghost", 55.0)
        spell("spell_resurrect_lesser_skeleton", 55.0)
        spell("spell_resurrect_lesser_zombie", 55.0)
        tele("spell_salvegrave_teleport", 30.0, CoordGrid(0, 53, 54, 40, 5))
        spell("spell_adept_reanimation", 80.0)
        spell("spell_inferior_demonbane", 27.0)
        spell("spell_shadow_veil", 58.0)
        tele("spell_fenkenstrainscastle_teleport", 50.0, CoordGrid(0, 55, 55, 28, 9))
        spell("spell_dark_lure", 60.0)
        spell("spell_skeletal_grasp", 33.0)
        spell("spell_resurrect_superior_ghost", 70.0)
        spell("spell_resurrect_superior_skeleton", 70.0)
        spell("spell_resurrect_superior_zombie", 70.0)
        spell("spell_mark_of_darkness", 70.0)
        tele("spell_westardougne_teleport", 68.0, CoordGrid(0, 39, 51, 4, 27))
        spell("spell_superior_demonbane", 36.0)
        spell("spell_lesser_corruption", 75.0)
        tele("spell_harmonyisland_teleport", 74.0, CoordGrid(0, 59, 44, 21, 51))
        spell("spell_vile_vigour", 76.0)
        spell("spell_degrime", 83.0)
        tele("spell_cemetery_teleport", 82.0, CoordGrid(0, 46, 58, 36, 51))
        spell("spell_expert_reanimation", 138.0)
        spell("spell_ward_of_arceuus", 83.0)
        spell("spell_resurrect_greater_ghost", 88.0)
        spell("spell_resurrect_greater_skeleton", 88.0)
        spell("spell_resurrect_greater_zombie", 88.0)
        spell("spell_resurrect_crops", 90.0)
        spell("spell_undead_grasp", 46.5)
        spell("spell_death_charge", 90.0)
        spell("spell_dark_demonbane", 43.5)
        tele("spell_barrows_teleport", 90.0, CoordGrid(0, 55, 51, 45, 50))
        spell("spell_demonic_offering", 175.0)
        spell("spell_greater_corruption", 95.0)
        spell("spell_master_reanimation", 170.0)
        tele("spell_arceuusapeatoll_teleport", 100.0, CoordGrid(0, 43, 142, 19, 13))
        spell("spell_sinister_offering", 180.0)
    }

    private fun spell(symbol: String, xp: Double) {
        val type = HashedObjType(null, symbol)
        edit(type) { param[params.spell_castxp] = (xp * 10).toInt() }
    }

    private fun tele(symbol: String, xp: Double, dest: CoordGrid) {
        val type = HashedObjType(null, symbol)
        edit(type) {
            param[params.spell_castxp] = (xp * 10).toInt()
            param[params.spell_telecoord] = dest
        }
    }
}
