@echo off
:: setup-rsprox.bat — write %USERPROFILE%\.rsprox\proxy-targets.yaml for local RSMod.
:: Reads the RSA modulus from rsmod\.data\client.key (generated by install-server.bat).
:: Safe to run repeatedly — overwrites the existing config.

setlocal

set "SCRIPT_DIR=%~dp0"
for %%A in ("%SCRIPT_DIR%..") do set "PROJECT_ROOT=%%~fA\"
set "RSMOD_ROOT=%PROJECT_ROOT%"
if exist "%PROJECT_ROOT%rsmod\gradlew.bat" set "RSMOD_ROOT=%PROJECT_ROOT%rsmod\"
set "CLIENT_KEY=%RSMOD_ROOT%.data\client.key"
set "RSPROX_CONFIG_DIR=%USERPROFILE%\.rsprox"
set "TARGETS_FILE=%RSPROX_CONFIG_DIR%\proxy-targets.yaml"

:: Optional overrides (for RSProx login stability triage).
:: - RSPROX_JAV_CONFIG_URL: override the jav_config.ws source (rev 233 default below).
:: - RSPROX_BOOTSTRAP_HASH: override the RuneLite bootstrap commit hash pinned into the target config.
set "JAV_CONFIG_URL=%RSPROX_JAV_CONFIG_URL%"
if "%JAV_CONFIG_URL%"=="" set "JAV_CONFIG_URL=https://client.blurite.io/jav_local_233.ws"

set "BOOTSTRAP_HASH=%RSPROX_BOOTSTRAP_HASH%"

if not exist "%CLIENT_KEY%" (
    echo [rsprox] ERROR: %CLIENT_KEY% not found.
    echo [rsprox] Run scripts\install-server.bat first to generate RSA keys.
    exit /b 1
)

:: Extract the modulus line (format: "Modulus: <hex>")
set "MODULUS="
for /f "tokens=2" %%M in ('findstr /b "Modulus:" "%CLIENT_KEY%"') do set "MODULUS=%%M"

if "%MODULUS%"=="" (
    echo [rsprox] ERROR: Could not parse modulus from %CLIENT_KEY%
    exit /b 1
)

:: Create ~/.rsprox directory
if not exist "%RSPROX_CONFIG_DIR%" mkdir "%RSPROX_CONFIG_DIR%"

:: Write proxy-targets.yaml
(
    echo config:
    echo   - name: "RSMod Local"
    echo     jav_config_url: "%JAV_CONFIG_URL%"
    echo     modulus: "%MODULUS%"
    echo     revision: "233"
    if not "%BOOTSTRAP_HASH%"=="" echo     runelite_bootstrap_commithash: "%BOOTSTRAP_HASH%"
    echo     game_server_port: 43594
) > "%TARGETS_FILE%"

echo [rsprox] proxy-targets.yaml written to: %TARGETS_FILE%
echo [rsprox] Modulus: %MODULUS%
echo [rsprox] jav_config_url: %JAV_CONFIG_URL%
if "%BOOTSTRAP_HASH%"=="" (
    echo [rsprox] runelite_bootstrap_commithash: ^<auto^> ^(from RSProx^)
) else (
    echo [rsprox] runelite_bootstrap_commithash: %BOOTSTRAP_HASH%
)

endlocal
