#!/usr/bin/env bash
# setup-rsprox.sh — write ~/.rsprox/proxy-targets.yaml for local RSMod.
# Reads the RSA modulus from rsmod/.data/client.key (generated by install-server.sh).
# Safe to run repeatedly — overwrites the existing config.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
RSMOD_ROOT="$PROJECT_ROOT"
if [ -f "$PROJECT_ROOT/rsmod/gradlew" ] || [ -f "$PROJECT_ROOT/rsmod/gradlew.bat" ]; then
    RSMOD_ROOT="$PROJECT_ROOT/rsmod"
fi
CLIENT_KEY="$RSMOD_ROOT/.data/client.key"
RSPROX_CONFIG_DIR="$HOME/.rsprox"
TARGETS_FILE="$RSPROX_CONFIG_DIR/proxy-targets.yaml"

if [ ! -f "$CLIENT_KEY" ]; then
    echo "[rsprox] ERROR: $CLIENT_KEY not found."
    echo "[rsprox] Run scripts/install-server.sh first to generate RSA keys."
    exit 1
fi

# Extract hex modulus from client.key (format: "Modulus: <hex>")
MODULUS=$(grep "^Modulus:" "$CLIENT_KEY" | awk '{print $2}')

if [ -z "$MODULUS" ]; then
    echo "[rsprox] ERROR: Could not parse modulus from $CLIENT_KEY"
    exit 1
fi

mkdir -p "$RSPROX_CONFIG_DIR"

cat > "$TARGETS_FILE" <<EOF
config:
  - name: "RSMod Local"
    jav_config_url: "https://client.blurite.io/jav_local_233.ws"
    modulus: "$MODULUS"
    revision: "233"
    game_server_port: 43594
EOF

echo "[rsprox] proxy-targets.yaml written to: $TARGETS_FILE"
echo "[rsprox] Modulus: ${MODULUS:0:16}... (${#MODULUS} hex chars)"
