package org.rsmod.content.skills.herblore.configs

import org.rsmod.api.type.refs.obj.ObjReferences

internal object HerbloreObjs : ObjReferences() {
    val grimy_guam = find("grimy_guam")
    val grimy_marrentill = find("grimy_marrentill")
    val grimy_tarromin = find("grimy_tarromin")
    val grimy_harralander = find("grimy_harralander")
    val grimy_ranarr_weed = find("grimy_ranarr_weed")
    val grimy_toadflax = find("unidentified_toadflax")
    val grimy_irit_leaf = find("grimy_irit_leaf")
    val grimy_avantoe = find("grimy_avantoe")
    val grimy_kwuarm = find("grimy_kwuarm")
    val grimy_snapdragon = find("unidentified_snapdragon")
    val grimy_cadantine = find("grimy_cadantine")
    val grimy_lantadyme = find("grimy_lantadyme")
    val grimy_dwarf_weed = find("grimy_dwarf_weed")
    val grimy_torstol = find("unidentified_torstol")

    val clean_guam = find("guam_leaf")
    val clean_marrentill = find("marentill")
    val clean_tarromin = find("tarromin")
    val clean_harralander = find("harralander")
    val clean_ranarr = find("ranarr_weed")
    val clean_toadflax = find("toadflax")
    val clean_irit = find("irit_leaf")
    val clean_avantoe = find("avantoe")
    val clean_kwuarm = find("kwuarm")
    val clean_snapdragon = find("snapdragon")
    val clean_cadantine = find("cadantine")
    val clean_lantadyme = find("lantadyme")
    val clean_dwarf_weed = find("dwarf_weed")
    val clean_torstol = find("torstol")

    val guam_potion_unf = find("guamvial")
    val marrentill_potion_unf = find("marrentillvial")
    val tarromin_potion_unf = find("tarrominvial")
    val harralander_potion_unf = find("harralandervial")
    val ranarr_potion_unf = find("ranarrvial")
    val toadflax_potion_unf = find("toadflaxvial")
    val irit_potion_unf = find("iritvial")
    val avantoe_potion_unf = find("avantoevial")
    val kwuarm_potion_unf = find("kwuarmvial")
    val snapdragon_potion_unf = find("snapdragonvial")
    val cadantine_potion_unf = find("cadantinevial")
    val lantadyme_potion_unf = find("lantadymevial")
    val dwarf_weed_potion_unf = find("dwarfweedvial")
    val torstol_potion_unf = find("torstolvial")

    val vial_of_water = find("vial_water")
    val eye_of_newt = find("eye_of_newt")
    val unicorn_horn_dust = find("unicorn_horn_dust")
    val limpwurt_root = find("limpwurt_root")
    val red_spider_eggs = find("red_spiders_eggs")
    val white_berries = find("white_berries")
    val snape_grass = find("snape_grass")
    val mort_myre_fungus = find("mortmyremushroom")
    val dragon_scale_dust = find("dragon_scale_dust")
    val wine_of_zamorak = find("wine_of_zamorak")
    val potato_cactus = find("cactus_potato")
    val jangerberries = find("jangerberries")
    val crushed_nest = find("crushed_bird_nest")

    val attack_potion_3 = find("3dose1attack")
    val antipoison_3 = find("3doseantipoison")
    val strength_potion_3 = find("3dose1strength")
    val restore_potion_3 = find("3dosestatrestore")
    val defence_potion_3 = find("3dose1defense")
    val prayer_potion_3 = find("3doseprayerrestore")
    val super_attack_3 = find("3dose2attack")
    val super_antipoison_3 = find("3dose2antipoison")
    val fishing_potion_3 = find("3dosefisherspotion")
    val super_energy_3 = find("3dose2energy")
    val super_strength_3 = find("3dose2strength")
    val super_restore_3 = find("3dose2restore")
    val super_defence_3 = find("3dose2defense")
    val antifire_3 = find("3dose1antidragon")
    val ranging_potion_3 = find("3doserangerspotion")
    val magic_potion_3 = find("3dose1magic")
    val zamorak_brew_3 = find("3dosepotionofzamorak")
    val saradomin_brew_3 = find("3dosepotionofsaradomin")
}
